### ISSUE TITLE
plugin configuration 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#10]
all the plugins need to be configured.

**Comment by alexpflores** [comment]
Blocked by #5

**Comment by jgrajkowski** [comment]
Used earlyyearsbc.ca as a benchmark for settings.  However, earlyyears is behind on a couple of updates whereas TLPDdev is generally current.  I'm not OK doing the WP+plugin update at the moment so have made things correlate as well as possible between pages and versions.

Completed plugins (all, per today's list of plugins installed on tlpddev):
- Piwik/Matomo (monitored on helga for now)
- Shariff (see #17 for some notes: this plugin coordinates with ShareThis-style links, with places we'd like users to share the link at, so I added Twitter, Facebook, and LinkedIn -- listing available BCcampus or TLPD accounts is done elsewhere)
- Relevanssi (I have "built the index". Once sufficient content exists, someone will have to index unindexed posts within the Relevanssi plugin.  A few minor changes (vs earlyyears) to Weights (Searching tab. Probably need to review the search Stopwords later.)
- Events Manager 
- Contact form (tlpd@bccampus.ca is a temporary test account, currently directing to helpdesk@bccampus.ca)
- Commons in a Box: minor setup updates to BuddyPress, InviteAnyone (**have yet to test invites)

EYPD also has the ContactFormDB plugin which is not presently installed on TLPD.

**Comment by jgrajkowski** [comment]
Procedural question:
Shall we move this to validation?  Or make note to make the suitable updates in the go-to-live sprint?

(updating: language that refers to the project name throughout the page and plugins, to the contact form/service email address, update Relevanssi index, and update Piwiki to troy.bccampus.ca)

**Comment by bdolor** [comment]
please move to validation - this sprint goal is limited in scope to the development instance.

**Comment by bdolor** [comment]
nice catch on the contactFormDB plugin - have installed and activated on dev

**Comment by jgrajkowski** [comment]
Made the necessary edits on ContactFormDB - by which I mean I think one thing in the integrations tab needed to be flipped to False.

There is a Contact Form shortcode created in EarlyYearsBC that I have yet to be able to create.
