### ISSUE TITLE
Background colour changes (to grey)

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/tlpd#101]
related to #61 

let's stick with greys instead of blues, so can we do #f7f7f7 for:

- this (footer bg)
- WP-header
- and header in the events-table tabbed content

... and should be white behind 'find learning events near you?

pleaseandthankyou

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/115

**Comment by BCcLeva** [comment]
The header in the events table needs to be changed to #f7f7f7

Need to change to white behind "Find Learning Events Near You"

Thanks!

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/6a5648a15460c99121439153af62ac96a4775f93
