### ISSUE TITLE
Footer changes: Margin on description paragraph + remove extra BCcampus logo

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/tlpd#104]
I've put the BCcampus logo in a dev-not-required image widget (see: Appearance > Widgets > Footer Right widget > Image for future changes) and adjusted column content in the footer.  This brought about multiple minor changes required.

- Please remove the 'hardcoded' BCcampus logo (unless there's a reason to do it this way)
- Change footer text size to approx 12px (it's 16 now, not sure if you're using hard px values or what, but discussion ended in 'smaller, please'. I think this is H5 so might need a new tag as H5 changes a lot of things...)
- Create more space between the page description paragraph and the 'About Us/etc' column
- Italicize "Teaching and Learning Professional Development portal (TLPD)" in blurb

Sorry 'bout the multi-task issue... brain dump before hurrying out of office. Flag it and I'll split 'em out into separate issues this afternoon.

**Comment by bdolor** [comment]
resolved via #113
