### ISSUE TITLE
Events page: Search Box display on Cell phone is misaligned

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#116]
### Description 
Alignment of Search boxes displayed on cell phone needs to be fixed.

![image-1](https://user-images.githubusercontent.com/34721375/46093992-a80fbd80-c16d-11e8-8b71-1f43115c2713.jpg)

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
please clear browser cache, and let me know which browser you are using so I can try and recreate the issue.

**Comment by bdolor** [comment]
closing
