### ISSUE TITLE
Footer display on Cell phone spacing correction 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#117]
### Description 
Need some line spacing between blurb and the linked text 
![image-2](https://user-images.githubusercontent.com/34721375/46094159-16ed1680-c16e-11e8-893d-68c1eff5ef68.jpg)

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
closing
