### ISSUE TITLE
Edit sentence at top of /sign-up/

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/tlpd#119]
Currently says:
"Fill in the fields below to register as an Organizer. Organizer — you are primarily posting training events on behalf of your organization."

Change to:
"Register as a Contributor to post professional learning events."

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/48ef0d41e2adc2961c062c393b66768b6c7702e7

**Comment by paulagaube** [comment]
This looks good on dev.
