### ISSUE TITLE
search categories 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#12]
What are these? We need them.

**Comment by BCcLeva** [comment]
Reviewing what I had done for this and will provide suggested SEARCH categories tomorrow.

**Comment by BCcLeva** [comment]
@bdolor is this something that is we as site admin can update and change or 
by web developers?

**Comment by bdolor** [comment]
These are event categories, as defined by the events manager plugin that is accessible to site admins

**Comment by BCcLeva** [comment]
Search Categories:

![image](https://user-images.githubusercontent.com/34721375/40134108-5c7434bc-58f6-11e8-814d-fe0c2fb759c3.png)

**Comment by BCcLeva** [comment]
Ok that's a long list but we can go with it. We will need to address how we categorize or note what is available as open resources on the web or learning that is self-directed.

**Comment by BCcLeva** [comment]
Ok I'll give it a go. Thanks Brad.

**Comment by BCcLeva** [comment]
@bdolor can I enter in any order and do an alpha sort for the display after or?

**Comment by BCcLeva** [comment]
ok super

**Comment by BCcLeva** [comment]
@bdolor if I've done what I can do and it needs to be checked or validated I move to the validate column right?

**Comment by bdolor** [comment]
yes, and if you're wanting someone else to validate that work for you, you would leave it in that column, otherwise, move it to done.

**Comment by BCcLeva** [comment]
If Searching multiple categories does  it search for entries with Category A OR Category B or Category A AND Category B?

**Comment by bdolor** [comment]
@paulagaube - the select list of categories in the search form on the homepage isn't controlled by anything in the admin interface.

**Comment by BCcLeva** [comment]
I'm good with it being a list where one Category selection is made at a time. I'm assuming the Categories are added to those events/items that that content is integral. 

The keyword search will capture whatever appears in the text of the blurb.

**Comment by paulagaube** [comment]
Sorry for the confusion, @BCcLeva and @bdolor I was looking at how to add multiple categories when creating a new event, as an organizer, and not the using the category drop down list on the home page search function.
