### ISSUE TITLE
Are we able to delete the Contributor role from User Profile Fields?

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/tlpd#120]
Presently configured to include Contributor as a default selection.

A few questions:

1. Is this connected to actual user configuration or is the WP contributor type automatically?
2. If it is required, how can we disable/hide? The visibility options provided don't seem to actually remove the item.

**Comment by bdolor** [comment]
If you could provide a link to a page please.

**Comment by jgrajkowski** [comment]
https://tlpd.bccampus.ca/wp-admin/users.php?page=bp-profile-setup

https://tlpd.bccampus.ca/sign-up/

**Comment by bdolor** [comment]
answered in https://github.com/BCcampus/tlpd/issues/95#issuecomment-425192868
