### ISSUE TITLE
Change Graphic on login page to TLPD logo

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#121]
### Description 
Mentioned in issue #93 - Change graphic for Login screen to the TLPD graphic
from the BCcampus graphic per @jgrajkowski question.

Carryover from last sprint to reinforce the site identity by changing the graphic on the login Screen to TLPD logo.Reflect branding by changing colour from Turquoise to TLPD dark green #006338

**Actual behaviour** 
The current logo appearing on the login screen is the BCcampus logo
![screen shot 2018-12-09 at 4 55 45 pm](https://user-images.githubusercontent.com/34721375/49705491-5b1b7f00-fbd3-11e8-8c1c-61a04c07f380.png)

### Steps to reproduce the problem
 "Login" on the Home page upper right hand

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Pretty sure she means https://tlpd.bccampus.ca/wp-login.php :)

**Comment by BCcLeva** [comment]
Yes I mean the Login screen as noted above.

**Comment by bdolor** [comment]
is the logo in question something we already have, or does it need to be created?

**Comment by jgrajkowski** [comment]
I believe just the TLPD logo in place of BCcampus logo.

I may make an adjustment to the logo tomorrow AM so feel free to hold off on this til then.

**Comment by jgrajkowski** [comment]
Updated logo in #129 or 
![tlpd-logo_final_1810](https://user-images.githubusercontent.com/39138174/46229735-75a3c300-c31b-11e8-993e-0ac63e3fd181.png)
[TLPD Logo_Final_1810_xo.zip](https://github.com/BCcampus/tlpd/files/2429497/TLPD.Logo_Final_1810_xo.zip)

**Comment by dshaykewich** [comment]
Resize to 249 x 96 px

**Comment by dshaykewich** [comment]
![tlpd](https://user-images.githubusercontent.com/43043264/49753672-f874c280-fc68-11e8-8b27-d823d6585af4.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/7a4c0abdcf423947560fd5be87d2bf7973d12284

**Comment by kkilbey** [comment]
I see the TLPD logo, but it looks a bit compressed height-wise. Is it possible to expand it to the natural height of 111 pixels, space permitting?

Also, the original issue description mentions changing the turquoise styling to TLPD dark green #006338. Is this a non-dev fix, or worth opening a new ticket? Let me know what you think, @bdolor and @paulagaube--thanks!

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/57297a058cf416f830d6e1088f0659e252e6f55b and https://github.com/BCcampus/tlpd/commit/8e3d67cde25ff46f6f2c6a5ce9f4dbb25a2cde0f

**Comment by kkilbey** [comment]
One last thing! The highlighted border that appears when you select the Username/Password fields or check the "Remember Me" box is still turquoise.

**Comment by kkilbey** [comment]
Both fixes look great! Note: we decided to leave Username/Password field highlights and "Remember Me" check box blue, as the colour fits with the TLPD palette. Moving to Done.

**Comment by kkilbey** [comment]
Looks good on Prod.
