### ISSUE TITLE
Fix map display on Cell phone

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#123]
### Description 
The display of the map on phone (iphone6). The map is skewed to the left. 
![cellphonemap](https://user-images.githubusercontent.com/34721375/46175112-bfc76e80-c25f-11e8-91b8-61fdbbefba49.jpg)

[Description of the bug or feature]

**Expected behaviour** 

Push pin of the location on the map is centered in the map frame.

**Actual behaviour** 

Push pin is pushed off to the left.

### Steps to reproduce the problem

Iphone 6 in Safari viewing event page.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Same happens on Android in portrait mode.
In landscape, map offset but fits.
![screenshot_20180927-141740](https://user-images.githubusercontent.com/39138174/46175318-690e6480-c260-11e8-9fb5-15bb2d2541f8.png)

**Comment by bdolor** [comment]
Looking at the issue template (please use it if you can) it has a line that asks what the expected behaviour is. In this particular issue the expected behaviour in landscape mode could be that it would allow date and time information to float beside the map, or it could be to take up the width of the screen. There are a few different ways to go on this one. Let us know what you want and we'll discuss if it's possible - thanks!

**Comment by jgrajkowski** [comment]
Let's say in both cases fit to max width of the text (retain margins). @BCcLeva care to weigh in?

**Comment by jgrajkowski** [comment]
Leva says yes to above (width of text).

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/31b85206265267c1829b162c137f51e05fc96f2f

**Comment by kkilbey** [comment]
This looks good for me on iPhone 6 in both portrait and landscape mode. Perhaps someone with an Android could also check? @BCcLeva?

**Comment by BCcLeva** [comment]
![map image iphone8](https://user-images.githubusercontent.com/34721375/49915525-f8ccb380-fe4a-11e8-8f86-ec4a76c8994a.jpg)
This is what it looks on an iphone8 ..still skewed to left. And note  the "+" sign to  max and min size of map and there are 3 of them and 3 "-"

**Comment by bdolor** [comment]
@BCcLeva - if it's rendering like that it tells me that your cache needs to be cleared.

**Comment by kkilbey** [comment]
@BCcLeva Also, I notice from the URL in your screenshot that you're on the prod site. I think the issue will only be fixed on dev for now, until changes are pushed to prod--is that correct, @bdolor ?

**Comment by bdolor** [comment]
@kkilbey eyes like an :eagle:

**Comment by BCcLeva** [comment]
yes indeed eyes like an eagle. Thanks. the image looks good on an Android as well.
