### ISSUE TITLE
Improve readability of Popovers 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#124]
### Description 
Dark text on Black Popovers are difficult to read.

![screen shot 2018-09-27 at 4 09 57 pm](https://user-images.githubusercontent.com/34721375/46179612-f6f24b80-c270-11e8-9d5c-7db21f1dc1fa.png)

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Let's go with the same soft grey background (#f7f8fc i think), text same as body text, same green links.

**Comment by BCcLeva** [comment]
Hi Brad sorry I didn't get back to you above since I didn't get a ping message.  Thanks Jen for jumping in. As our designer Jen I'd be looking to you for advice on the hex colours anyway.

**Comment by bdolor** [comment]
closing, not relevant with respect to https://github.com/BCcampus/tlpd/issues/133
