### ISSUE TITLE
Change the highlight color for calendar dates on the Date picker 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#125]
### Description 

Hover colour on the pop-up calendar date picker does not match site colour palette.
![screen shot 2018-09-27 at 10 02 54 pm](https://user-images.githubusercontent.com/34721375/46189036-73048780-c2a1-11e8-854f-f79b6f2b018a.png)
**Expected behaviour** 

Hover colour on the calendar matches the site colour palette while still being 'accessible'. For example, a lighter shade of purple-gray (such as #9f73ae) (rather than the yellow/orange) which is in keeping with the current colour palette .

**Actual behaviour** 

Orange/yellow hover colour.

### Steps to reproduce the problem
Pop open date picker and hover over dates.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
Dave will provide colour choices

**Comment by dshaykewich** [comment]
Use #DBC8DF as background colour.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/dbda1a0b0e7e0cb3a90cb64e0cf895673bb63abd

**Comment by kkilbey** [comment]
Both the current date colour and the hover-over date colour are displaying correctly for me. Moving to Done.
![image](https://user-images.githubusercontent.com/44710357/50122714-b3c1cc00-0212-11e9-9a69-ac2925480b88.png)

**Comment by kkilbey** [comment]
Done on Prod.
