### ISSUE TITLE
Fix how logo appears in Safari

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#126]
### Description 
In older versions of Safari v 10.1.2, the TLPD logo takes up the whole screen and pushes all content below the fold.

![screen shot 2018-09-28 at 10 35 54 am](https://user-images.githubusercontent.com/34721375/46224928-8a2c8f00-c30c-11e8-9fa0-a6c8d5d654a0.png)

**Expected behaviour** 

On newer versions of Safari (e.g., iPhone 6), the logo is proportionally the right size.  Expect the same proportions on older versions of Safari

**Actual behaviour** 

In older versions of Safari v 10.1.2, the TLPD logo takes up the whole screen and pushes all content below the fold.

### Steps to reproduce the problem

Obverved on older Mac laptop with Safari (10.1.2) and iPad 2 Safari (9)

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by dshaykewich** [comment]
Appears fixed.

**Comment by dshaykewich** [comment]
Issue does not seem to occur on iPhones, but on iPad the logo is very large.

**Comment by bdolor** [comment]
will need to investigate

**Comment by BCcLeva** [comment]
This is done. Decision made only support more recent versions of Safari. 
We can identify what version of Safari is the cutoff and note this in our documentation and on Help page if necessary.
