### ISSUE TITLE
Hide the Organizer radio button and "Role (Required)" text on the Sign Up page 

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#127]
### Description 

On the TLPD Sign Up page: https://tlpddev.bccampus.ca/sign-up/, under "Create an Account" > Profile Details, hide the words "ROLE (REQUIRED)" and the Organizer radio button. (Use CSS?)

**Expected behaviour** 

A user will not see the text "Role (Required)" or the "Organizer" radio button on the Sign Up page. The functionality of this radio button (user signs up as an Organizer) will need to remain for the Validate by Domain plugin. (But the user doesn't need to see this as an option.)

**Actual behaviour** 

The ROLE (REQUIRED) Radio button shows that "Organizer" is the only option.

### Steps to reproduce the problem
See image below.

Go to https://tlpddev.bccampus.ca/sign-up/
<img width="576" alt="signup-page-hide-radio-button" src="https://user-images.githubusercontent.com/26391359/46225651-c9f47600-c30e-11e8-8d60-b3706fc429ea.png">

### System Information

- TLPD: Dev and Prod
- WordPress: current version

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/validate-by-domain/commit/d581085bfa2ba47ea794569ab93cfa23ee2f93f0 

@paulagaube - the change was made to `validate by domain` plugin which no longer requires that the `Organizer` field/radio button (set in BuddyPress) be present. 

The `white list` of email domains will be checked. Leaving the `Field Number` at the default '0' (Tools->Validate By Domain) will by-pass the Organizer/Learner functionality required for EYPD, but not for TLPD.

![image](https://user-images.githubusercontent.com/2048170/49965268-94086c00-fed1-11e8-8367-48433ad5b500.png)

The dashboard process that will need to coincide with master branch deployment for Prod will be to delete the Organizer radio button from the buddypress dashboard and set the field number in Validate by Domain to 0

**Comment by BCcLeva** [comment]
yes looks good! Verified on Macbook and iphone.

**Comment by paulagaube** [comment]
@bdolor on the Sign-Up page, the Organizer button still appears on PROD though does not appear on Cert. Also, the change with the Agreement Terms at the bottom of the page are not on the Sign-Up page either. "Terms of Use" is not showing and needs to link to the modal window https://tlpd.bccampus.ca/sign-up/#terms (issue #128)

**Comment by BCcLeva** [comment]
The Organizer button is hidden in PROD. Done.
The Terms of Use is linked to content which appears in Popup. Done

**Comment by paulagaube** [comment]
This issue was fixed by going to Users > Profile Fields and deleting the "Organizer" Field.
