### ISSUE TITLE
Update TLPD logo wherever it occurs

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/tlpd#129]
### Description 
Update logo

**Expected behaviour** 

Please use the attached updated logo
[This includes (at least) header, PWA probably, and updating the login-page logo per item #121.]

**Actual behaviour** 

Showing outdated version of the logo

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here] 

[TLPD Logo_Final_1810_xo.zip](https://github.com/BCcampus/tlpd/files/2429484/TLPD.Logo_Final_1810_xo.zip)
![tlpd-logo_final_1810](https://user-images.githubusercontent.com/39138174/46229577-f2826d00-c31a-11e8-9afa-720ae133b62f.png)

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/b3cf62de84bd4f63c8540724bd0337b66e26ec1a

**Comment by kkilbey** [comment]
Looks good--done on Prod.
