### ISSUE TITLE
BP member sidebar (lower left) requires widget update

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/tlpd#131]
Example (replace jgrajkowski with your username or access your profile while logged in via some other means: https://tlpddev.bccampus.ca/members/jgrajkowski/profile/edit/group/1/ 

See: https://tlpd.bccampus.ca/wp-admin/widgets.php > Homepage Center Widget 

I added the _(BuddyPress) Recently Active Members_ widget to match the dev site but it's still just showing "BP Member Sidebar" below the profile controls despite cache clears, etc.

These profile pages likely need some thorough review for clarity and visibility.

Might become a dev issue if that widget doesn't show up. Maybe I'm missing a checkbox. Dunno.  ;)

**Comment by paulagaube** [comment]
I fixed this by going through the widgets, comparing CERT against PROD. There are a couple differences.
I added two widgets to the "Member Sidebar": (1) "(BuddyPress) Who's Online: Who's Online" and (2) (BuddyPress) Recently Active Members: Recently Active Members"
Removed those same two widgets from the "Homepage Center Widget" space and this fixed the problem of the widgets displaying on DEV.
This is DONE, but @kkilbey could you check please?

**Comment by kkilbey** [comment]
Both of the widgets appear in both CERT and PROD for me. @paulagaube I'd say Done as well!

**Comment by kkilbey** [comment]
Done in Prod.
