### ISSUE TITLE
Update Google Account used to access maps API

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#132]
### Description 

Currently, Brad's personal Google account is being used to access Google APIs for embedding maps into the site.  There is now a 'devops' account, which should be used instead.

**Expected behaviour** 

Use the "devops@bcccampus.ca" google account to access google maps apis.

**Actual behaviour** 

Using Brad's personal account.

**Comment by bdolor** [comment]
this is complete
