### ISSUE TITLE
Hide navigation links when not logged in

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#133]
### Description 

Selectively show navigation links based on 'logged in' status and change labels of links.

![screen shot 2018-12-04 at 3 08 56 pm](https://user-images.githubusercontent.com/43043264/49479172-e9a88e80-f7d6-11e8-9aa1-b6cd9e476428.png)

**Expected behaviour** 

Links appropriate for logged in users should only display for logged in users:  
 - Show "Edit Events" and "My Events" only when logged in.

Change label of "Events" to "View Events"
Change label of "Add New" to "Add Event"

**Actual behaviour** 

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/a05cae413aa14a679d04b03f124a8057ec997a9a
