### ISSUE TITLE
Review and consolidate locations

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#134]
### Description 

There are events for both "British Columbia" and "BC".  Events need to be cleaned to use only "BC".

**Expected behaviour** 

"British Columbia" should not be displayed as a 'Province' in the search form.

**Actual behaviour** 

There are events for both "British Columbia" and "BC" in the Province drop-down of the event search form.

### Steps to reproduce the problem

View search form.  Click 'Show Advanced Search' to display the 'Province' form field.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by BCcLeva** [comment]
Yep. Done

**Comment by kkilbey** [comment]
Done on Prod.
