### ISSUE TITLE
Add event contact email address 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#135]
### Description 

When creating an event, there is no ability to provide a contact email address for the event.

**Expected behaviour** 

Contact email address available for event.

**Actual behaviour** 

There is no email address associated with an event (only phone number)

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/6166207a6e7ce94942ed179ce94051684f18de44

**Comment by BCcLeva** [comment]
Email address added to form. Works. All good.

**Comment by paulagaube** [comment]
DONE on Prod
