### ISSUE TITLE
No webcam access for Change Avatar - Take a Photo

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#136]
### Description 

The Change Avatar page offers users the option to "Upload" a profile photo or to "Take Photo." When I select "Take Photo," I see a message saying "Please allow us to access to your camera," but there are no instructions for how to allow access (see image below). Also note the duplicate "to" in the camera access message.
![image](https://user-images.githubusercontent.com/44710357/49675749-d17d7d00-fa2b-11e8-89e1-93c9fd4b202f.png)

If I then select "Capture," the message changes to say "Please wait as we access your camera" (see image below), but nothing happens.
![image](https://user-images.githubusercontent.com/44710357/49676361-46ea4d00-fa2e-11e8-9f43-d2b394f1f337.png)

**Expected behaviour** 

This may require further discussion, but given the current set up of the Take Photo page, I would expect to see an option to turn on my webcam next to the message that says "Please allow us to access your camera." Then, I would expect to see the camera feed in the box, and I would expect the "Capture" button to take a photo, which I could then save or discard and take a new photo.

**Actual behaviour** 

There is nothing I can select that will activate/allow access to my webcam, and so I cannot take a profile photo from the Take a Photo page.

### Steps to reproduce the problem

Log in to TLPD.
Click on your name in the upper right-hand corner.
From the left sidebar menu, select "Change Avatar."
Select the "Take Photo" tab.

**Comment by paulagaube** [comment]
Tested and now working. Closing this issue.
