### ISSUE TITLE
Ensure Website field becomes hyperlinked

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#137]
### Description 

The Post an Event page contains a custom field titled "Website," where contributors can include the URL for their own, external event page. Currently, URLs entered into this field do not become hyperlinked when the event is saved. This means that when a user views an event, they cannot click on the URL and be quickly directed to more info.

We also had this issue during the EYPD sprint. See that ticket here: https://github.com/BCcampus/eypd/issues/120

Proposed Conditions of Acceptance (based on what we learned from the EYPD issue linked above):
- URL in the Website field becomes a hyperlink when a new event is saved
- Website field only accepts valid URLs--if an invalid URL is entered, an error message appears upon clicking "Post Event" that says "Website is not a valid URL"
- If Website field is left blank, the error message does not appear
- If contributor omits "https://" from URL, the hyperlink adds it. (This was a problem in EYPD: if the event poster omitted the https:// then the link would redirect to an error page.)

**Expected behaviour** 

When a new event is saved, the URL entered into the Website field becomes a hyperlink.

**Actual behaviour** 

When a new event is saved, the URL entered into the Website field remains plain text.

### Steps to reproduce the problem

Either:
1. Go to TLPD (no need to log in)
2. Select Events and choose an event to view
3. Scroll down to website field to see URL

Or:
1. Log in to TLPD as contributor
2. Select Add New and create an event
3. Enter a URL in the Website field
4. Post event and scroll down to website field to see URL

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/25fcddbc07f363eee8e826bf25b5daf420d6bd54

**Comment by paulagaube** [comment]
@bdolor Tested the Website field on tlpddev and this does not work. 
Created this new event:  https://tlpddev.bccampus.ca/events/tidy-tuesday/

For the URL, I added "peavi.ca" first, then when that didn't work, entered "https://peavi.ca" and re-saved the event. This also does not display an URL on the website. (The link appears to be plain text only.)

**Comment by bdolor** [comment]
ah, we are not calling this field 'Registration Link'...okay...re-resolved via https://github.com/BCcampus/tlpd/commit/bdd3513399ee1f371920849682b1945403dc9104

**Comment by paulagaube** [comment]
Thanks, this works now! The site is looking gooooood......

**Comment by paulagaube** [comment]
@bdolor one question about this: do the Website URLs in existing events need to be re-entered and re-saved so that the website links will work?

**Comment by paulagaube** [comment]
DONE in Prod
