### ISSUE TITLE
Enable ability to search by geographic region in BC

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#138]
### Description 
Currently there is no pick list or ability to search by a region in BC

**Expected behaviour** 
Be able to go to the Search by Region box and pick a region to perform a search for events taking place in that region. The selected regions can be these:
https://www.welcomebc.ca/Choose-B-C/Explore-British-Columbia/Regions-in-B-C
(or a simplified version used by Edplanner BC uses https://educationplannerbc.ca/)

**Actual behaviour** 
What happens now is there are no selections available for region and user cannot search by region.

### Steps to reproduce the problem
Go to the home page and show "Advanced Search". 
![screen shot 2018-12-09 at 3 00 35 pm](https://user-images.githubusercontent.com/34721375/49704216-03761700-fbc5-11e8-926f-f081c059855d.png)

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/a89bb4911f76644a26e714863deee04f87da46c0
note: this has re-enabled the regions text field for locations. Having regions show up in the search area as a drop down list requires data to be entered first (of course)
