### ISSUE TITLE
Cleanup display of Date on Event description page

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#139]
### Description 
The word "Date(s)" is repeated  under the heading "Date/Time" which is redundant. 

**Expected behaviour** 
Immediately after the heading "Date/Time" I would expect to see the month, day year for the event and the time as applicable. 

**Actual behaviour** 
What we see is "Date(s)" and then the month etc. 

### Steps to reproduce the problem
Search for an event. Display the event description. 

![screen shot 2018-12-09 at 3 24 20 pm](https://user-images.githubusercontent.com/34721375/49704338-a3807000-fbc6-11e8-9590-faf745613b3e.png)

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/b880677fda646169e8929abbcac5e9591266b18f

**Comment by kkilbey** [comment]
This looks good to me! I no longer see the extra "Date(s)" on event description pages.

**Comment by kkilbey** [comment]
Looks good on Prod.
