### ISSUE TITLE
post an event page (remove features)

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#14]
On the post an event page, there are a number of content items (programmatically controlled) that need to be vetted. 

- get rid of Certificate Hours 
- get rid of Certificate option 

![image](https://user-images.githubusercontent.com/2048170/36688884-a37aae9c-1ae2-11e8-9a83-46394982205e.png)

**Comment by alexpflores** [comment]
completed via https://github.com/BCcampus/tlpd/commit/f37c5dfdb8da0bd29140b7a594fc50d9d70ade4f
