### ISSUE TITLE
Posting an Event: Selecting Categories 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#140]
### Description 

When posting an event, a Contributor needs to use various control keys to select more than one Category. An easier method to select multiple categories would make this more user-friendly. e.g. user suggested Check boxes.

Also providing Contextual information such as Category definitions would be helpful.

**Actual behaviour** 
Currently  user needs to use control keys etc. "To select multiple items [mac]=command,click [pc]=ctrl,click"  There is no contextual help such as definitions /examples for the Categories.

### Steps to reproduce the problem
Login as a Contributor. Add an Event. Go to "Category"
![screen shot 2018-12-09 at 5 35 20 pm](https://user-images.githubusercontent.com/34721375/49707159-fa923f00-fbde-11e8-9ad3-f52badc1bedf.png)

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
will investigate

**Comment by kkilbey** [comment]
Neat solution! This is done.

**Comment by kkilbey** [comment]
Done on Prod.
