### ISSUE TITLE
Posting an Event: Remove "Availability"

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#141]
### Description 
 Remove "Availability" as a field from the Posting an Event page. This information is not necessary and confusing for users. 

### Steps to reproduce the problem
Go to "Add an Event" and "Availability". 
![screen shot 2018-12-09 at 6 50 10 pm](https://user-images.githubusercontent.com/34721375/49708170-52cb4000-fbe3-11e8-82e5-a0c10eb7b681.png)

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/93632226c8b2b3c1fb3b540938b3eeb3921dc624

**Comment by kkilbey** [comment]
Done on Prod.
