### ISSUE TITLE
Change capital "S" to lowercase

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#142]
### Description 
Fix the capitalization on 2 fields in the Event Posting page.

The "S" is capitalize within the parentheses of "Presenter(s)" and "Prerequisite(s)"
![screen shot 2018-12-09 at 6 58 32 pm](https://user-images.githubusercontent.com/34721375/49708615-3203ea00-fbe5-11e8-82b7-76557ea0514c.png)

**Comment by paulagaube** [comment]
Updating this ticket with a new image, because now we have three capital S'ssssssss:
<img width="309" alt="capital-s-bad" src="https://user-images.githubusercontent.com/26391359/50020944-50bf0380-ff8c-11e8-8645-6378fe516bde.png">

**Comment by bdolor** [comment]
oh cute...it happens in Chrome and treats `(s)` as the beginning of a new word. Firefox seems smarter in this regard.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/89e61f2e6fe997e2c735ef9b90186fbd89945a82

**Comment by BCcLeva** [comment]
Looks good. S's are lower case.

**Comment by kkilbey** [comment]
Done on Prod.
