### ISSUE TITLE
Posting an Event page: Change Field Labels 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#143]
### Description 
Change "Presenters" to "Facilitator Name(s)"
Change "Presenter Information" to "Facilitator(s) Bio"
![screen shot 2018-12-09 at 7 21 49 pm](https://user-images.githubusercontent.com/34721375/49709123-b8b9c680-fbe7-11e8-9e66-af2136431e20.png)

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by dshaykewich** [comment]
Leva to provide instructional content.

**Comment by BCcLeva** [comment]
For "Faciltator Bio(s)" the text field description reads:

"Maximum 100 words"

**Comment by BCcLeva** [comment]
Hi @bdolor this should now be unblocked.

**Comment by bdolor** [comment]
thanks @BCcLeva - are you also wanting to enforce a maximum word length, or is this merely suggestive?

**Comment by BCcLeva** [comment]
suggestive is fine. Thanks.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/95db1eeb35f72cf7b0f22cca18c85e6b63950bec

**Comment by kkilbey** [comment]
Done on Prod.
