### ISSUE TITLE
Posting an Event: Remove "Registration Space"

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#144]
### Description 
On the Event Posting page, remove "Registration Space" as a field.
![screen shot 2018-12-09 at 7 36 21 pm](https://user-images.githubusercontent.com/34721375/49709579-ee5faf00-fbe9-11e8-9071-a4d66b547834.png)

Expected Behavior is that user logged in as a Contributor will not see this as a field option when posting an event.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
@BCcLeva - I don't see this field on tlpddev so can safely assume that it's not a valid issue.

**Comment by kkilbey** [comment]
I also don't see this field on tlpddev, so I will move this to Done.

**Comment by kkilbey** [comment]
Looks good on Prod.
