### ISSUE TITLE
Change 3rd Column of "Find Learning Events Near You" on Home Page

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#145]
### Description 
The "Availability" Column is no longer needed since we don't want to collect this information. Replace with the hyperlinked URL for the event.

**Expected behaviour** 
People can look at the list of events under "Find Learning Events Near You" and click on the website to go to the source site immediately.

**Actual behaviour** 
Users are not finding the "Availability" information useful and Contributors find it confusing. We are eliminating it. 
![screen shot 2018-12-09 at 6 43 14 pm](https://user-images.githubusercontent.com/34721375/49709734-b6a53700-fbea-11e8-9382-7c4decda19da.png)

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
Will investigate replacing the availability column with the Location field on the homepage. If it looks to be too onerous, we will look at removing it

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/cee1ff3cf62dc079f7f7c1219a4b73b329a54233

**Comment by kkilbey** [comment]
Looks good! This is done.

**Comment by kkilbey** [comment]
Done on Prod.
