### ISSUE TITLE
Account Registration Confirmation Message - Add TLPD logo branding colours

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#146]
### Description 
The confirmation message has no TLPD branding. 
Remove the red stripe on the screen and replace with dark green #006338 and add the TLPD logo.

![acct reg message](https://user-images.githubusercontent.com/34721375/49710004-d426d080-fbeb-11e8-85c0-7ce3145a1a98.png)

### Steps to reproduce the problem
Follow process to signup for an account.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by kkilbey** [comment]
@BCcLeva I have replaced the red stripe with dark green. Would you like to change the beige background colour, too, or is that okay?
![image](https://user-images.githubusercontent.com/44710357/50174970-7e6bbb80-02b0-11e9-9703-ae5d0ed22a49.png)

**Comment by BCcLeva** [comment]
If you can chg to the light gray.

**Comment by kkilbey** [comment]
Ok, updated on Cert and Prod. Moving to validating.

![image](https://user-images.githubusercontent.com/44710357/50176502-6bf38100-02b4-11e9-9e28-92e23021c7bd.png)

**Comment by BCcLeva** [comment]
Beauteous. Done.

**Comment by kkilbey** [comment]
Done on Prod.
