### ISSUE TITLE
"Upcoming Events" - Make display of City/Town more readable

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#148]
### Description 
Display of the listing under "Upcoming Events" needs to be streamlined. Display the City/Town to the same line as the event title so it looks less cluttered.
**Actual behaviour** 
![screen shot 2018-12-09 at 8 13 59 pm](https://user-images.githubusercontent.com/34721375/49710602-68466700-fbef-11e8-8590-ad787a0de589.png)

### Steps to reproduce the problem

Go to Home page. Click on "Events" and first item. "Facilitating Learning Online"
to see the "Upcoming Events" listing.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment]
@BCcLeva can we discuss this issue please?

**Comment by BCcLeva** [comment]
yes I will be available this AM until 10/10:AM. I will be available if there is a standup.

**Comment by BCcLeva** [comment]
The goal is to make this more readable. Perhaps play around with the stying...space to distinguish the groupings.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/a52047b2e7eb936e2451e1b1c0573af5059f8dce

**Comment by BCcLeva** [comment]
Looks better. Done.

**Comment by kkilbey** [comment]
Looks good on Prod--done!
