### ISSUE TITLE
Posting an Event" Add some contextual help to "Online" field

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#149]
### Description 
When posting an event the field "Online" requires additional contextual help.

Add: "Is this offering available online or provide opportunities for online participation?"

**Expected behaviour** 
The user will be able to select "Yes" or "No" more readily with additional info,

**Actual behaviour** 
There is no text to help/prompt the user and feedback received is more clarification is needed.
![screen shot 2018-12-09 at 8 21 54 pm](https://user-images.githubusercontent.com/34721375/49710831-caec3280-fbf0-11e8-9348-c1d14ab5938f.png)

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by dshaykewich** [comment]
No longer relevant.
