### ISSUE TITLE
Posting an Event: Change contextual info.

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#150]
### Description 
When Posting an event under "Where", the contextual info needs to be changed.

Currently: "If your event is online fill in the location fields based on the location of the organization sponsoring this event."
Change to: "If your event is online fill in the location field based on the location of the event organizers."

![screen shot 2018-12-09 at 8 31 23 pm](https://user-images.githubusercontent.com/34721375/49711012-ca07d080-fbf1-11e8-86af-5b186f42c7ca.png)

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by dshaykewich** [comment]
CHanged procedure for posting events.
