### ISSUE TITLE
Popup for Date search doesn't display properly

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#151]
### Description 
When using the date search the popup doesn't display properly. The heading for the month is cutoff.

**Expected behaviour** 
The header and the month to display when using the popup for the date search box.

**Actual behaviour** 
The heading doesn't show. Cutoff at the top.
![screen shot 2018-12-09 at 8 38 22 pm](https://user-images.githubusercontent.com/34721375/49711159-b0b35400-fbf2-11e8-9f0a-38dddbb8beaf.png)

### Steps to reproduce the problem
Do a date search on the Home page.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
seems that this appears under certain conditions with screen sizes and where in the vertical scroll the user is.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/c67f4455b6660854683a4984dbcd1f2353b1eadb

**Comment by kkilbey** [comment]
This looks good on Prod.
