### ISSUE TITLE
Contact Us form on Android cell phone

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#152]
### Description 
Contact Us form when displayed on the Android cell phone seems too large for display. User needs to
scroll left/right and fields are cut off on the right.
(The form appears nicely centred on a Apple iphone)

**Expected behaviour** 
The display of the Contact Us form is centred on the screen of the Android phone.

**Actual behaviour** 
The display skews to the right/off centre/field boxes cutoff on right.
![screenshot_2018-12-02-12-33-20](https://user-images.githubusercontent.com/34721375/49741138-9907ba00-fc4a-11e8-97fd-bfd7903cdb9f.png)

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/343272a92612f1cbe523f007681a5b98469aae70

**Comment by BCcLeva** [comment]
Looks magnificent. Done!
