### ISSUE TITLE
Update Content discrepancies between TLPD DEV and PROD Sites

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#153]
### Description 
Update any Content discrepancies between TLPD DEV and PROD Sites. There are some differences due to work being doing on the PROD site and not updated on the DEV.  

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment]
@BCcLeva I started comparing CERT and PROD on the Dashboard> Appearance > Widgets and made some adjustments, but noticed the menu on the bottom is different between CERT and PROD sites, so this still has to be fixed/updated. There is more to do on this issue.

**Comment by paulagaube** [comment]
@BCcLeva The Event Categories on Cert and Prod do not match exactly. Could you please confirm if the categories on Prod are the ones you want to use going forward? 

I've only copied the categories that are not the same here:

Category labels in CERT (tlpddev)
Educational Assessment and Evaluation
Facilitation Skills
Policy
Technology

Category labels in PROD (tlpd)
Assessment and Evaluation **
Ed Development
Ed Policy
Facilitation
Instructional Skills
Online Learning

**Comment by BCcLeva** [comment]
I've reviewed the Categories and as they stand they are:
Assessment and Evaluation
Curriculum Development
Diversity and Inclusion
Ed Development
Ed Policy
Ed Technology
Facilitation
Instructional Skills
Learning Design
Open Education
Organizational Change and Development
Scholarly Teaching and Learning
Scholarship of Teaching and Learning

**Comment by kkilbey** [comment]
I have made the following items consistent on Cert and Prod:
- Locations, including Regions and Provinces in Search menu (Cert needed updating to match Prod)
- Provinces drop-down menu on Sign-Up page (Cert needed updating to match Prod)
- Help page (Cert had outdated info re: posting an online event)
- BCcampus logo in footer (Cert had old "15" logo)
- About Us page (small grammatical changes on both Cert and Prod)
