### ISSUE TITLE
Account Activation Page: Hide activation Key

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#155]
### Description 
The display of the Account Activation key is confusing.  Hide the key and just show the
Activate button.

**Expected behaviour** 
The user sees the Activate button and clicks on it.

**Actual behaviour** 

The user sees both the Activation Key and the button and gets confused as what to do.

![image](https://user-images.githubusercontent.com/34721375/49744078-e9821600-fc50-11e8-832d-d50f4c3a6dd9.png)

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/60e899f035e25df8407f03b3ed06dd198e27e013

**Comment by kkilbey** [comment]
Done on Prod.
