### ISSUE TITLE
Add more prominent Login to Activation page 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#156]
### Description 
Once Account is activated, login should be easy to do. The Login button is small and easily missed by a new user (upper right Hand corner)

**Expected behaviour** 
A new User does not have to look for the Login button. It should be readily available.

**Actual behaviour** 
New user needs to look for the Login on the Account activated page.
![image](https://user-images.githubusercontent.com/34721375/49744480-b7bd7f00-fc51-11e8-8a06-4defd5cbd397.png)

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/8ef7e1f3e4aa12a5b648e36b86e8b8218f26ec82

**Comment by kkilbey** [comment]
Confirmed: done on Prod.
