### ISSUE TITLE
Account User Icon Page colours 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#157]
### Description 
User story:
As an account user/Contributor with a visual disability I need a high contrast colours so that I may read text on the screen.

The Account icon display of black on green is difficult to read because it is not high contrast.

![image](https://user-images.githubusercontent.com/34721375/49744761-5f3ab180-fc52-11e8-9cbc-dba417458eba.png)

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by dshaykewich** [comment]
Dave to determine plain text and link colour.

**Comment by dshaykewich** [comment]
![tlpd-user-pop-open-closed](https://user-images.githubusercontent.com/43043264/49821787-25d87380-fd30-11e8-91fb-0c91dbb095f9.png)

![tlpd-user-pop-open-hover](https://user-images.githubusercontent.com/43043264/49821805-2f61db80-fd30-11e8-87f3-6d768cd6a2a9.png)

![tlpd-user-pop-open-hover-off](https://user-images.githubusercontent.com/43043264/49821817-37218000-fd30-11e8-93b3-5cdf1568bd10.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/736625b5ed05258ce6e0ce8d1a73afd01e20b92c

**Comment by BCcLeva** [comment]
white on green is much better. Fixed. Done. Thanks.

**Comment by kkilbey** [comment]
Looks great--done on Prod.
