### ISSUE TITLE
My TLPD Account Page: wording 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#158]
### Description 
Change the wording on the Account Contributor Profile page (don't want reference to "training"/typo). We need to be clear on what is to be referenced on this page before providing wording. (I need a consult -LL)

![image](https://user-images.githubusercontent.com/34721375/49745157-2b13c080-fc53-11e8-9114-e0126af14f4a.png)

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
only keep my events. remove all other text.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/aece0f9b832c19260bdd0a6089e3974367e11e1a

**Comment by kkilbey** [comment]
Done on Prod.
