### ISSUE TITLE
Post Event Page: help text

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#159]
### Description 

Review and improve language and prompts for completing form (what is mandatory or not and examples)
![screen shot 2018-12-10 at 8 57 27 am](https://user-images.githubusercontent.com/34721375/49748292-23a3e580-fc5a-11e8-839a-4846db3d813b.png)

Provide more clarity in prompts so user can complete form with more ease. 

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by BCcLeva** [comment]
Modify or Add text descriptions for Event Name, Where, Event Hosts, Online as noted in red on screenshots.
![event hosts online - text description](https://user-images.githubusercontent.com/34721375/49920235-5d453e00-fe5e-11e8-9b96-d4d21c9efbcf.png)
![event name - text description](https://user-images.githubusercontent.com/34721375/49920237-5dddd480-fe5e-11e8-9d16-604fba199f52.png)
![where -text description](https://user-images.githubusercontent.com/34721375/49920240-5e766b00-fe5e-11e8-874c-220a6a55da2d.png)

**Comment by BCcLeva** [comment]
@bdolor over to you. Ignore the last arrow I couldn't remove. Thx

**Comment by BCcLeva** [comment]
Note: For "Event Name" and "Where" Please delete the text that is in place and replace with what's in red. Thanks @bdolor 
(I couldn't get the tool to work to cross off in the diagram.)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/032a16f1ef105ad75eb47017c9d60dc93be41d94

**Comment by BCcLeva** [comment]
Completed as requested.

**Comment by paulagaube** [comment]
@BCcLeva I'd like to talk about this issue before it gets closed, as the grammar on the "Online" text is not correct, and our investigation of the best way to post "online" events continues. The text under "Where" may also have to change again since we created the "Web" location. Or we remove the "Web" location, which has other ramifications.

**Comment by paulagaube** [comment]
DONE on Prod
