### ISSUE TITLE
Icons on Google map show in triplicate

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#160]
### Description 
The [] , + and - icons are showing in triplicate on the google map.
![screen shot 2018-12-10 at 11 15 54 am](https://user-images.githubusercontent.com/43043264/49755383-789d2700-fc6d-11e8-9c16-1d052f48a41c.png)

**Expected behaviour** 

Should just show one instance of icons.

**Actual behaviour** 

Showing icons in triplicate.

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by dshaykewich** [comment]
Can't replicate.

**Comment by dshaykewich** [comment]
Triplicate icons _are_ showing when on the 'post an event' page (though showing correctly on the event details page).
https://tlpd.bccampus.ca/post-event/

**Comment by alex-418** [comment]
I cannot replicate it (in Chrome,FireFox,Safari, or IE 11) but can see the same fix that was applied to EYPD already does exists in TLPD:
https://github.com/BCcampus/tlpd/blob/ca12419cc1268ffad8ffa1d28d857880595670e3/assets/styles/components/_map.scss#L22

Maybe the cache needs to be clear on the browser that was tested? @dshaykewich Please let me know if you are still seeing this issues on TLPD (and EYPD) after clearing browser cache.

**Comment by dshaykewich** [comment]
Here's what I'm seeing this morning on my Mac:

Chrome:
![screen shot 2019-02-20 at 8 28 44 am](https://user-images.githubusercontent.com/43043264/53107429-db226700-34e9-11e9-931f-945506ec2342.png)

Safari:
![screen shot 2019-02-20 at 8 29 06 am](https://user-images.githubusercontent.com/43043264/53107456-e83f5600-34e9-11e9-8cd9-3e19069d92ad.png)

Firefox
<img width="897" alt="screen shot 2019-02-20 at 8 29 32 am" src="https://user-images.githubusercontent.com/43043264/53107499-fc835300-34e9-11e9-9fed-87852c45991f.png">

**Comment by kkilbey** [comment]
I'm also seeing the icons a bit off centre in both Cert and Prod. This occurs only on the Event info pages, not on the Post an Event page.
Windows 10 / Edge:
![image](https://user-images.githubusercontent.com/44710357/53108084-3ef95f80-34eb-11e9-9017-071d733b431c.png)

**Comment by paulagaube** [comment]
@alex-418 I have checked the tlpddev site using Chrome on Windows 10 and the + and - symbols look the same as Dave's above: not triplicate anymore, but off-center. Here:
![image](https://user-images.githubusercontent.com/26391359/53108197-75cf7580-34eb-11e9-86f7-80ebf8b95009.png)

**Comment by kkilbey** [comment]
@alex-418 @paulagaube @dshaykewich I'll move this back to "To Do" for now.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/610740ca6a93ffbbe2d18d83f50e76cdb38fdc2a

**Comment by kkilbey** [comment]
Looks good on Chrome, Firefox, and Edge (PC/Windows 10). @dshaykewich could you confirm for Mac?

**Comment by dshaykewich** [comment]
Looks good on Chrome, Firefox and Safari on Mac.  

@kkilbey , I'll leave this to you to move to done.

**Comment by kkilbey** [comment]
Roger that! Moving to Done.
