### ISSUE TITLE
Move "No Categories" text under heading

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#161]
### Description 

If a contributor posts an event without selecting any categories, the event page lists "No Categories" beside the heading "Categories." In other fields, text appears beneath the field heading (see image below). For consistency, "No Categories" should also be modified to display beneath the heading rather than beside it.

![image](https://user-images.githubusercontent.com/44710357/49769756-62f02780-fc96-11e8-98e8-abf67ab364d6.png)

**Expected behaviour** 

If an event is posted with no categories selected, the text "No Categories" appears beneath the heading "Categories."

**Actual behaviour** 

If an event is posted with no categories selected, the text "No Categories" appears beside the heading "Categories."

### Steps to reproduce the problem

1. For an example of this issue, visit the ETUG Spring Workshop event info page at this link: https://tlpd.bccampus.ca/events/etug-spring-workshop-2019/

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/4e8d9184cd1f31d76cd5c3fdc1bbe13991c6b0f2

**Comment by kkilbey** [comment]
Looks great! Moving to Done.
![image](https://user-images.githubusercontent.com/44710357/53056077-c947b200-345e-11e9-97a5-a9cbb8a9172b.png)

**Comment by paulagaube** [comment]
Yes, this is done on Prod too.
