### ISSUE TITLE
Post an Event - Extend drop-down fields

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#162]
### Description 

Some drop-down fields on the Post an Event page are too short, so that the plus sign obscures the text (see Target Audience field or Event Is Open To External field in image below). Extend these fields so that text and plus sign do not overlap.

![image](https://user-images.githubusercontent.com/44710357/49770217-49e87600-fc98-11e8-9953-12eb0df9f530.png)

Fields that require extending (all drop-downs):
- Timezone
- Location
- Target Audience
- Event Is Open To External
- Online
- Availability (will be deleted as per issue #141)

This also occurs in myTLPD > Notification Settings > Archives drop-down menu
![image](https://user-images.githubusercontent.com/44710357/50122350-e965b580-0210-11e9-863d-2516b4691780.png)

**Expected behaviour** 

Fields are long enough to include text and plus sign without overlap.

**Actual behaviour** 

Fields are too short, causing text and plus sign to overlap.

### Steps to reproduce the problem

1. Log in as a Contributor or Admin
2. Click "Add New" to go to the Post an Event page
3. Fill in drop-down fields to see text/plus sign overlap

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/d36ab58aef54f22cb965fc204e55d06f4a67cd4b

**Comment by kkilbey** [comment]
@bdolor All looks good on the Post an Event Page!

There is still a bit of overlap on the Archives drop-down (My Events > Notification Settings). Could you please extend that field a little, too?
![image](https://user-images.githubusercontent.com/44710357/53052520-d1e6bb00-3453-11e9-896a-93c00e4f331b.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/a34f4ac238d53169d366d2ec36d74767f610dfd8

**Comment by kkilbey** [comment]
Perfecto! Thanks @bdolor Moving this to "Done."
