### ISSUE TITLE
Posting an Event: Uneven spacing between custom fields

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#163]
### Description 

On the Post an Event page, some custom fields have a bit of space above their heading, such the "Target Audience - Other" field in the image below. However, some custom fields have almost no space above their heading, such as the "Event Hosts" field. In the sprint planning meeting, we decided it would look less cluttered if all the fields had some space above their heading (the amount of space between "Target Audience" and "Target Audience - Other" is ideal). Change so field spacing is consistent.

![image](https://user-images.githubusercontent.com/44710357/49815210-19e4b580-fd20-11e8-8102-d05a2b828c89.png)

**Expected behaviour** 

There is an equal amount of space between each field on the Post an Event page.

**Actual behaviour** 

The amount of space between fields on the Post an Event page is inconsistent.

### Steps to reproduce the problem

1. Log in to TLPD as a Contributor or Admin
2. Select "Add New" to go to the Post an Event page
3. Scroll down below "Categories" to see the custom fields/spacing

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/tlpd/commit/57eaaf8f68cddc5523d0b73ea757977df19f252a. Added the same spacing as the others: 8px

**Comment by kkilbey** [comment]
@alex-418 Looks good! I think "Category" and "Facilitator Name(s)" are still a bit close together. Could you apply the same spacing between those two fields? :)
![image](https://user-images.githubusercontent.com/44710357/53109023-e7f48a00-34ec-11e9-8aff-b894bc8dcef0.png)

**Comment by alex-418** [comment]
Done via https://github.com/BCcampus/tlpd/commit/3dab26344b54bc8821f193e4df29e18e3d3949d1

**Comment by kkilbey** [comment]
Perfect, thank you @alex-418! Moving this to "Done."
