### ISSUE TITLE
change hardcoded text to widget in footer

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#164]
### Description 

hardcoded text bad (5)
widgetized function wanted (7)
better. yahoo. ya. (5)

**Expected behaviour** 

Content owners should have access to modify all the content. 

**Actual behaviour** 

The content is hardcoded which makes people sad. 

### Steps to reproduce the problem

look at the footer and try to change the text. you probably can't unless you're me.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/39c05ac816444fe9e9d74193aa05356dd855c5d5 note: There are three widget areas in the footer, `Left`, `Middle` and `Right` - use a custom HTML widget for `Footer left` once on prod.

**Comment by BCcLeva** [comment]
Perfect! Thanks! Moving to Done!

**Comment by paulagaube** [comment]
DONE in Prod. 
Created a new "middle bottom menu" in Appearance > Menus (copied from Cert)

Added this Menu to the "Footer Middle" widget in Prod in Appearance > Widgets 
(Replaced the text links that were there)
