### ISSUE TITLE
Add Regions Field to Post Event page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#165]
### Description 

We have added "Region" as an advanced search option on the homepage, so we need to also add a "Region" field on the Post an Event page. However, we need to discuss the best way to go about this, @BCcLeva @paulagaube. Could it be incorporated into Locations? Will it need to be a separate field formatted as a drop-down menu? Is it a required field? How will this affect the Online location?

Note: we will also need to manually assign regions to pre-existing events in both Cert and Prod.

**Expected behaviour** 

Contributors can select a region when posting an event, so that users can search for events by region.

**Actual behaviour** 

There is nowhere for contributors to select a region, and so users cannot search for events by region.

**Comment by bdolor** [comment]
The location settings for events manager is currently configured to display locations as a drop down list...which prevents the region field (or any other location field for that matter) from displaying. A simple toggle of the radio button will re-enable all location fields and the ability to add new locations to events.

![image](https://user-images.githubusercontent.com/2048170/50178504-96940880-02b9-11e9-9ab2-f20f3116e6b9.png)

**Comment by bdolor** [comment]
From a data model perspective, regions are a field under the Locations umbrella: 
![image](https://user-images.githubusercontent.com/2048170/50186923-3f9a2d80-02d1-11e9-8732-786ef1ee1b89.png)

**Comment by paulagaube** [comment]
Ah, ok. More testing from us needed then.

**Comment by kkilbey** [comment]
Since Regions are tied in to Locations, which we have set as a fixed drop-down menu, this ticket is no longer relevant (thanks for clarifying above, @bdolor!).

I have made sure regions/locations are consistent in Cert and Prod, so the Search by Region function will work as expected. Ok to move this to "Done" @paulagaube?

**Comment by paulagaube** [comment]
@kkilbey Yes! thank you. Looks good.
