### ISSUE TITLE
Minor Fixes to Post an Event Page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#166]
### Description 

Make the following minor edits to the Post an Event page: https://tlpddev.bccampus.ca/post-event/

- Under **Event Name**: move informational text above text entry box and change to:
_E.g., "Instructional Skills Workshop"_

- Under **Where**: change informational text to:
_If your location is not on this list, [contact us](https://tlpddev.bccampus.ca/contact-us/) for assistance._ (Cert)
_If your location is not on this list, [contact us](https://tlpd.bccampus.ca/contact-us/) for assistance._ (Prod)

- Under **Event Description and Objectives**: remove parentheses around informational text:
_What will participants learn?_

- Under **Registration Fee**: replace single quotations around 'Free' and 'No fee for internal staff' with double quotations:
_"Free" and "No fee for internal staff"_

- Please make the **Facilitator(s) Bio** text field larger to allow more text to be visible at once. E.g., extending the width to 400 px and, if possible, tripling the row height.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/ce23c40b937b1441b0c353bee17a7601181a192e

**Comment by kkilbey** [comment]
Done on Prod.
