### ISSUE TITLE
Post an Event: Remove "No groups defined yet" Text

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#167]
### Description 

On the Post an Event page, a line of text that says "No groups defined yet" appears beneath the Event Name field. Please remove this text.
![image](https://user-images.githubusercontent.com/44710357/50360739-e53dde80-0515-11e9-8111-4d8a6a216da8.png)
Link to Post an Event page: https://tlpd.bccampus.ca/post-event/

**Expected behaviour** 

The Post an Event page displays only the necessary and helpful text that we expect to see.

**Actual behaviour** 

The Post an Event page displays a mysterious line of text that we do not want to see.

### Steps to reproduce the problem

1. Log in as an Admin or Contributor and visit the Post an Event page (https://tlpd.bccampus.ca/post-event/)
2. Observe mysterious text below Event Name field

**Comment by alex-418** [comment]
Completed...this was related to BuddyPress "groups" functionality. I have disabled this unnecessary feature which removed the message on this form.

**Comment by kkilbey** [comment]
Fabulous. Moving to Done!
