### ISSUE TITLE
Replace BCcampus "15" logo with new logo

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#168]
### Description 
The old BCcampus 15 logo is showing in the footer of TLPD.bccampus.ca

**Expected behaviour** 

Add the new BCcampus logo 

**Actual behaviour** 

Old logo showing in footer

### Steps to reproduce the problem

go to tlpd.bccampus.ca
look in the footer at the BCcampus logo

### System Information

- TLPD: current version
- WordPress: current version

**Comment by alex-418** [comment]
New footer logo added on prod.

**Comment by kkilbey** [comment]
Confirmed--looks good! Moving to "Done on Prod."
