### ISSUE TITLE
Change text above Search box

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#169]
### Description 
On the TLPD Home page and the Events listing page, in the Search area, the text above the first search box needs to be updated to say "Search by Keyword (topic, location, institution, etc.)"
https://tlpd.bccampus.ca/
https://tlpd.bccampus.ca/events/

![image](https://user-images.githubusercontent.com/26391359/52746250-f2b39a00-2f95-11e9-84d6-59f4d8791f76.png)

**Expected behaviour** 

The text above the first search box will say: **Search by Keyword (topic, location, institution, etc.)**

**Actual behaviour** 

The text above the search box currently says:  Search by Topic, Keyword or Location

### Steps to reproduce the problem (and to validate)

View the text on the search field at the top of this page: https://tlpd.bccampus.ca/
View the text search field at the bottom of this page: https://tlpd.bccampus.ca/events/

The text now says: "Search by Topic, Keyword or Location."

Change this text to: "Search by Keyword (topic, location, institution, etc.)"

### System Information

- TLPD: PROD
- WordPress: 5.0.3

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/172

**Comment by kkilbey** [comment]
Awesome, this looks good on both the home page and the Events page. Moving to Done.
