### ISSUE TITLE
social media icons

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#17]
we need to know which social media sites to include 

- linkedin
- twitter

**Comment by BCcLeva** [comment]
LinkedIn
https://www.linkedin.com/company/bccampus

Twitter
@BCcampus

**Comment by jgrajkowski** [comment]
As noted in the meeting, this service is more about what platforms you want to enable people to share using.  I have put the common 3 (twitter, facebook, linkedin).

Listing/advertising/providing a direct the BCcampus accounts is a separate task (usually icons in the footer or on a contact us page).

**Comment by bdolor** [comment]
I created a test event to confirm that the social media icons appear as expected. To validate, @BCcLeva can you confirm that the icons are: 
1. the flavours of social media you want
2. the look and feel you want
3. the placement on the page you want.

if so, move this issue to DONE

**Comment by BCcLeva** [comment]
I've reviewed and 
1. social media selection is good twitter, FB and Linkedin
2. **please change to round icons similar to EYPD**
3. placement on page is good

Then it's DONE
Thanks.
