### ISSUE TITLE
Some required fields on post an event page missing asterisk

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#171]
### Description 

The follow fields are required for creating an event, but their labels do not have an asterisk indicating they're required.

-"When"
-"Where"
-"Registration Fee"

**Expected behaviour** 

All required fields should have asterisk indicating they're required.

**Actual behaviour** 

Some required fields do not have asterisk.

![screen shot 2019-02-13 at 11 06 10 am](https://user-images.githubusercontent.com/43043264/52737009-24ba0180-2f80-11e9-86a2-55258c30f8c9.png)
### Steps to reproduce the problem

https://tlpd.bccampus.ca/post-event/

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/59a3446196a3b5c32e5514ea99707c0a14e6eacd

**Comment by kkilbey** [comment]
Looks good! Moving to Done.
