### ISSUE TITLE
(Re-)enable Matomo for tlpd.bccampus.ca

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/tlpd#182]
### Description 

As with EYPD, no stats have been collected for the TLPD prod site since Matomo was moved. Please re-enable Matomo for tlpd.bccampus.ca so we can begin tracking stats again. Thank you!

**Expected behaviour** 

Matomo is collecting stats for tlpd.bccampus.ca

**Actual behaviour** 

Matomo does not appear to be collecting any data for tlpd.bccampus.ca

**Comment by dshaykewich** [comment]
Reenabled.
