### ISSUE TITLE
search analytics

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#19]
relevanssi plugin search and configuration set up. Would like to be able to look at who searched what for analytics

**Comment by jgrajkowski** [comment]
@bdolor 
done this afternoon.  done the initial index and basic configuration based on EYPD selections.

moving to validation.

**Comment by bdolor** [comment]
The indexing options did not match on the two sites, so updated to include:

- location
- event
- event-recurring
- category
- event-tags
- event-categories

**Comment by jgrajkowski** [comment]
which two sites?  (EYPD vs TLPDdev? or TLPDdev vs TLPD?)

**Comment by bdolor** [comment]
earlyyearsbc, eypd and tldpdev all had different configurations. earlyyearsbc is the 'source of truth' for all intents and purposes
