### ISSUE TITLE
server infrastructure 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#2]
investigate whether or not using the existing set up for eypd can be used for this project. 

Can we turn the eypd site (cert/prod) into a multisite instance?

**Comment by alexpflores** [comment]
Depends on the outcome #21, other non-technical benefits include the sharing of costs with the eypd server.

**Comment by alexpflores** [comment]
Some thoughts on multi-site: If we're handing off EYPD off in the near future, then perhaps creating this dependency on EYPD using multi-site is overkill? This may be better suited for a longer-term project, where we could take full advantage of spinning up similar sites, and realizing the benefits of using a common parent theme that we control. It also adds some slight overhead to use multisite specific functions for some things, and graceful fallback when it's stand-alone. Thoughts?

**Comment by alexpflores** [comment]
Working on making cert multi-site to help with #21. (Service workers cannot be registered locally due to https. which limits our ability to investigate that further.) 

Turned my local into multi-site, fixed a few errors when plugins were not activated via https://github.com/BCcampus/eypd/commit/48f69b3f22eb1965a0adf50148489bb53632b7a4

**Comment by alexpflores** [comment]
Our parent theme CBOX brings BuddyPress Core bundled along with other plugins (bbpress, etc) as required dependencies. This may cause problems, as there is no way to enable/disable the CBOX bundled plugins on a site per site basis. Also, I cannot see the CBOX settings menu in multi-site , investigating further. https://wordpress.org/support/topic/multisite-179/

**Comment by bdolor** [comment]
Buddypress is designed to behave differently on multisite vs single site. Unlike wp there is no clear separation in the database for different sites using buddypress on a multisite. The data from one site gets mixed with the other. Effectively, this is a **deal breaker** for multisite.
