### ISSUE TITLE
Sign up page content and functionality

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#20]
once a decision is made about registration, then we need to take a look at the content and functionality on the existing sign up page. 

- content
- links 
- functionality

**Comment by alexpflores** [comment]
Depends on #22

**Comment by bdolor** [comment]
@BCcLeva — now that #22 has been decided upon, you'll need to take a look at this issue and identify the differences that your sign up page will have from the existing one. https://earlyyearsbc.ca/sign-up/

**Comment by BCcLeva** [comment]
not sure if I'm supposed to assign to myself or not but I'm look at this now

**Comment by BCcLeva** [comment]
I can do a screen capture with annotation but wondering how best to send info to you? Maybe Word not good.

**Comment by bdolor** [comment]
not too concerned about which format...whatever works for you and gets the information in front of us. If you're happy working with Word - you can take a screen capture of what you do in Word and copy/paste or drag and drop that screen grab into the comments section here.

**Comment by BCcLeva** [comment]
ok let me try that and see if readable

**Comment by BCcLeva** [comment]
[T&LPortalORGANIZERPROFILEV2.docx](https://github.com/BCcampus/tlpd/files/1773331/T.LPortalORGANIZERPROFILEV2.docx)

ok there's a certain lameness in using MSword. I had done these screenshots earlier (posted v1) and updated but it won't let me annotate the logo on upper left without shifting. I basically want to note the BC and eypd logos are swapped out with our logo/placeholder logo. 

I'll provide list of "Professional Interests" or  "Topics" next

**Comment by BCcLeva** [comment]
Professional Interests

![image](https://user-images.githubusercontent.com/34721375/36926429-a5fafbe8-1e2c-11e8-9fea-92b8c16666a5.png)

**Comment by BCcLeva** [comment]
[profInterests.txt](https://github.com/BCcampus/tlpd/files/1776817/profInterests.txt)

**Comment by BCcLeva** [comment]
This is a list gleaned from our Survey results which should serve ok for the "prototype". Will I have ability to edit?

**Comment by BCcLeva** [comment]
or I guess we are staging...so everything subject to tweaking modifications...
