### ISSUE TITLE
Performance and PWA Audit coming back with low scores

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#23]
Concerned with the slow load speed of the website despite our extensive efforts to improve both page speed and PWA readiness, what has changed that killed our score? 

**1.) Performance score of 22** 
![slow](https://user-images.githubusercontent.com/17072191/36703930-ddf5db48-1b12-11e8-93ee-45ab8c8298a7.png)

**2.) Audit currently complains it's too slow to meet the 3G PWA baseline**
![pwa](https://user-images.githubusercontent.com/17072191/36703937-e1ba6cb2-1b12-11e8-869b-e518d10399bf.png)

**Comment by alex-418** [comment]
To investigate

**Comment by bdolor** [comment]
Related to PWA performance is actually getting to it to work without errors. One of the things that's needed to move this forward are the varying size of images that are used as buttons/icons on different devices. 

@jgrajkowski The goal will be to replace the existing EYPD icons with equivalent sizes, branded for TLPD. Images and sizes can be found here: https://github.com/BCcampus/tlpd/tree/dev/assets/images/pwa

**Comment by jgrajkowski** [comment]
So, not the favicons as provided in sprint 1?

**Comment by jgrajkowski** [comment]
I'll get something with the other sizes over, though are these actually viewed at those sizes? (i.e. 512)

I'll do TLPD instead of the +... probably. Back to you today with that.

**Comment by jgrajkowski** [comment]
Try these :)
[TLPD PWA.zip](https://github.com/BCcampus/tlpd/files/2416305/TLPD.PWA.zip)

**Comment by bdolor** [comment]
performance numbers from lighthouse testing against tlpddev.bccampus.ca is better, add to homescreen functionality works on android: 

![image](https://user-images.githubusercontent.com/2048170/46108543-2c286c00-c193-11e8-9f57-625ab6e6a600.png)
 
room for improvement noted, but this is now working with moderate performance results
