### ISSUE TITLE
reconfigure validate-by-domain plugin 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#27]
with respect to https://github.com/BCcampus/pro-d/issues/22#issuecomment-369688212 validate-by-domain needs to be refactored to allow for multiple configurations/allow lists. 

https://github.com/bccampus/validate-by-domain/

**Comment by alexpflores** [comment]
Currently sets the user role to "editor", this should be contributor in TLPD

**Comment by alexpflores** [comment]
Creating an options page to allow the user to set the following two options: 

**Whitelist** - Let's the user add/remove items from their list of valid domains which may register. 
**User Role** - The role the user will be given upon registering, the default being contributor.

**Comment by alex-418** [comment]
This is complete for our purposes, but also triggered a bigger list of issues that I'm having trouble ignoring. Please see https://github.com/BCcampus/validate-by-domain/issues I'm chipping away at those today.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/validate-by-domain/pull/19

**Comment by alex-418** [comment]
Continuing on https://github.com/BCcampus/validate-by-domain/issues while we wait for the database #24 to created.

**Comment by bdolor** [comment]
alpha release (works for our two use cases, but not likely for any others) https://github.com/BCcampus/validate-by-domain/releases/tag/1.2.0-alpha
