### ISSUE TITLE
logos and images

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#3]
we need the all the branding materials that will make this site not eypd

- header image (logo)
- banner image 
- footer image

**Comment by BCcLeva** [comment]
From email?

    the eypd logo in the header is a .png file https://github.com/BCcampus/eypd/blob/dev/assets/images/eypd-logomark.png 
    in the banner below the navigation on the main page, there are two .svg images 
        https://github.com/BCcampus/eypd/blob/dev/assets/images/eypd-logo-final-text.svg
        https://github.com/BCcampus/eypd/blob/dev/assets/images/eypd-logo-final.svg
    In the footer there is one .png file https://github.com/BCcampus/eypd/blob/dev/assets/images/eypd-logo-small.png


If you wanted to replicate the Progressive Web App functionality there are five .png files that need to be created https://github.com/BCcampus/eypd/tree/dev/assets/images/pwa

**Comment by alex-418** [comment]
@jgrajkowski to provide

**Comment by jgrajkowski** [comment]
Logo/wordmark:  ![tlpd-logo_final_201806](https://user-images.githubusercontent.com/39138174/41255806-99a82038-6d7c-11e8-8493-0eba3eaa6015.png)

BCcampus 15 for footer: 
![bccampus15logo_240x200](https://user-images.githubusercontent.com/39138174/41255966-17a03d2c-6d7d-11e8-94cb-8025133cdb94.png)

**Comment by jgrajkowski** [comment]
Moving this and other completed design items back to backlog for dev to take care of.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/7620ee61e3ff649851ca476c278f3859946dc92b
