### ISSUE TITLE
Online Form for Contact Us 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#32]
### Description 
Online form for contact us page 
[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment]
Jen was looking at the contact form this afternoon and was asking about what email address we want to use. I think she said the domain name needs to match the name of the site. 
I have created an email forwarder to use for the form, which is: tlpd@bccampus.ca.

Mail sent to this address will now go to helpdesk@bccampus.ca for now.
