### ISSUE TITLE
Research how to add an event without a start or end date

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#33]
### Description 

We would like to be able to add events that are links to online resources. These do not have a date as they may be self-directed resources.

**Expected behaviour** 

Online learning resources show up on a list of "events" and have a description that includes a link to the resource.

**Actual behaviour** 

All events must have a start and end date associated with them.  

Is this something that can be changed within the events plug-in? Research the possibility of adding these additional resources.

**Comment by alex-418** [comment]
Not possible with events manager, will have to look at other options.
