### ISSUE TITLE
Replace"MyTLPD" with "Events"

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#34]
### Description 
On the event page there is text that says "My TLPD" on  left underneath the calendar. Remove this text.

![screen shot 2018-05-17 at 2 48 06 pm](https://user-images.githubusercontent.com/34721375/40205772-407aaf88-59e2-11e8-9827-6c5a666596d9.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/44
