### ISSUE TITLE
Replace favicon 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#35]
### Description 
There is a favicon graphic of a hand that is used for EYPD.
Remove it. 
![screen shot 2018-05-17 at 3 23 26 pm](https://user-images.githubusercontent.com/34721375/40206807-7aef3ae0-59e6-11e8-9302-bd0799fb6f70.png)

**Comment by alex-418** [comment]
@jgrajkowski to provide new favicon

**Comment by jgrajkowski** [comment]
![favicon](https://user-images.githubusercontent.com/39138174/41255669-23c9bd22-6d7c-11e8-9be2-d416681eee3d.jpg)

**Comment by bdolor** [comment]
We can use the above 16x16 file...There are other sizes and formats to consider, https://github.com/audreyr/favicon-cheat-sheet - depending on how you want this icon to show up/display on different devices with different resolutions and screen size.

**Comment by jgrajkowski** [comment]
[TLPD Favicons.zip](https://github.com/BCcampus/tlpd/files/2091867/TLPD.Favicons.zip)

This should be almost the full set (I didn't do the wide ones).

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/commit/109b895a6bf7f73e81f75a837c3380ea7bd678c6
