### ISSUE TITLE
Make the Top section look like the mockup

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#37]
as per mockup

**Comment by alex-418** [comment]
@jgrajkowski need the plus icon please

**Comment by jgrajkowski** [comment]
Mockup again:

[Tlpd CSS edits mockup v3 20180611.pdf](https://github.com/BCcampus/tlpd/files/2091669/Tlpd.CSS.edits.mockup.v3.20180611.pdf)

**Comment by jgrajkowski** [comment]
Plus file provided in 41 and via email.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/2681269adddbd77792cc02f27fd58ef91f6fc9bf
