### ISSUE TITLE
Add back New + Noteworthy section

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#38]
As per mockup (no date needed), pull in events and posts (new and noteworthy category.)

**Comment by alex-418** [comment]
@jgrajkowski to provide generic default icon

**Comment by jgrajkowski** [comment]
Yep, it's pretty generic
![tlpd_bannerplaceholderv1](https://user-images.githubusercontent.com/39138174/41257798-05e142ba-6d83-11e8-8bf7-639ae57b6fb8.png)
