### ISSUE TITLE
Make bottom section look like mockup

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#39]
Map removed, waiting on new mockup for any additional changes.

**Comment by alex-418** [comment]
Tabs: 
Upcoming Events | New Events (same logic) | New Resources | New Opportunities

**Comment by jgrajkowski** [comment]
[Tlpd CSS edits mockup v3 20180611.pdf](https://github.com/BCcampus/tlpd/files/2091604/Tlpd.CSS.edits.mockup.v3.20180611.pdf)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/50
