### ISSUE TITLE
Default new and noteworthy icon

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#40]

**Comment by alex-418** [comment]
@jgrajkowski to provide, blocks #38

**Comment by jgrajkowski** [comment]
Yep, it's pretty generic 
![tlpd_bannerplaceholderv1](https://user-images.githubusercontent.com/39138174/41257828-144f88c0-6d83-11e8-888d-80cd2d71a0ef.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/46 ... if a post belonging to category 'Homepage' does not have a thumbnail image associated with the post it defaults to the above image.
