### ISSUE TITLE
Suggested if preload campus addresses: SFU Vancouver, SFU Burnaby, SFU Surrey

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#55]
### Description 

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
This is related to creating an event.
