### ISSUE TITLE
Add Event function: Use the range of 7 AM to 7 pm as default. Not midnight.

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#56]
### Description 

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
This is part of the events plugin, there is likely no hook/filter to allow us to change this easily.

**Comment by dshaykewich** [comment]
Won't fix.
