### ISSUE TITLE
Profile for Contributor Account holder: remove Consent

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#57]
### Description 

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
Need more information on what content to remove.

**Comment by alex-418** [comment]
Duplicate.

**Comment by alex-418** [comment]
This is related to the sign up page. Keeping this due to GDPR compliance suggest Positive opt-in: Get Positive opt-in (no pre-checked box) from users if they wish to use their data for export.
