### ISSUE TITLE
Events Results Page: Order of the Display

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#59]
### Description 

Events Results Page: Why do we display the Search box Above the Results Listing? Is it possible to display the results listing first and the Search Box below?

![image](https://user-images.githubusercontent.com/34721375/45655523-8475b480-ba95-11e8-9dd5-efaaf7b5624a.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
Searchbox in the events page has been moved via #100
