### ISSUE TITLE
Resolve current issue with account creation & authentication

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#60]
### Description 

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
Bring in the fix from EYPD

**Comment by paulagaube** [comment]
The fix is in and users are not asked for an activation key to validate the account. Done.
