### ISSUE TITLE
Footer Blurb: Replace with New Content

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#61]
### Description 

New footer blurb: "B.C.'s post-secondary educators can promote and join their colleagues in professional development opportunities for teaching and learning around the province. The Teaching and Learning Professional Development portal (TLPD) is sponsored by BCcampus."

![image](https://user-images.githubusercontent.com/34721375/45653045-61de9e00-ba8b-11e8-989d-347560eb3f69.png)

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
Footer text updated via https://github.com/BCcampus/tlpd/commit/ab6dbba578694ea8ecc5eb617fb60eb4c5a07301

**Comment by BCcLeva** [comment]
Is the colour of the footer block controlled by us as users? Is it a function of the widget that will be in place? I wanted a hyperlink from the BCcampus logo to BCcampus.ca. 
The blue is too dark now @jgrajkowski @alex-418  can you advise on what we should use..I was thinking light or nothing that stands out too much.

**Comment by alex-418** [comment]
@BCcLeva the color of the footer comes from the stylesheet, so it can't be changed by the user, as well as the the logo image link. If the logo link and footer color aren't going to change often, I would say there's no real need to widgetize them. The benefit of widgetizing is when the content changes often. Happy to link the logo image, and change the color if you can provide me with the hex value.

**Comment by jgrajkowski** [comment]
moving this to done and creating new issues for related CSS and design changes
