### ISSUE TITLE
Home Page:  Move Search Boxes 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#62]
### Description 

Tighten up use of space on the  main page search.
Move Province and City search boxes to the same line as Category.

![image](https://user-images.githubusercontent.com/34721375/45655162-9e15fc80-ba93-11e8-870d-864e3dbcda41.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/102
