### ISSUE TITLE
Rename + padding item displayed as "Capacity" to "Availabliity"

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#63]
### Description 

In tabbed Find Learning Events section, rename Capacity column to Availability (or similar, or remove entirely), and move capacity column to be column 2 (avoid giant gap between)

![image](https://user-images.githubusercontent.com/34721375/45655064-20ea8780-ba93-11e8-82c4-b603c59b7c3b.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Alternate, probably-preferred option:  Change width of main description column/cels so they're less crowded against the date column.

**Comment by alex-418** [comment]
Completed via #98

**Comment by BCcLeva** [comment]
The text under the headings **Date/Time,** **Event** and **Availability** are not flush with the headings. They are slightly offset. Can this be adjusted for better readabilty?

**Comment by alex-418** [comment]
@BCcLeva updated event table padding via https://github.com/BCcampus/tlpd/commit/254b8b98336cdc7a716869d6e9fc629fe70431d7 the headings had 8px padding, so I've added the same padding to the content as well.
