### ISSUE TITLE
CC Footer Fix

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#64]
### Description 
CC footer has weird line break (after a comma, unnecessarily)

![image](https://user-images.githubusercontent.com/34721375/45654934-ad487a80-ba92-11e8-9143-27a0225bf6aa.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Options:  
1. Remove line break and keep it with image left-aligned, OR
2. Move CC footer text to new line.

**Comment by bdolor** [comment]
should be resolved via https://github.com/BCcampus/tlpd/commit/6f5343d7cdc841fb8ce370237f1556bd1ccfc6fc will require clearing browser cache to validate
