### ISSUE TITLE
 New + Noteworthy posts: Update placeholder graphic 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#65]
### Description 

Update placeholder image for New + Noteworthy 

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
replacement placeholder/default image for "New + Noteworthy" items

![tlpd-newevent_placeholder_confetti1](https://user-images.githubusercontent.com/39138174/45636574-f1208d00-ba5c-11e8-9da0-e87cdda10e69.png)

**Comment by jgrajkowski** [comment]
![tlpd_neweventplaceholder_confetti_x600](https://user-images.githubusercontent.com/39138174/45970147-a10c7200-bfea-11e8-9995-1ecd53ba182d.jpg)

**Comment by alex-418** [comment]
New placeholder image added via https://github.com/BCcampus/tlpd/pull/103
