### ISSUE TITLE
Database Search terms for province 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#66]
### Description 

Lock down Province terms in search/db. Currently has BC and British Columbia based on entries, with different cities that show up.

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Pre-populate provinces?  Discussion required on whether to populate cities.

**Comment by paulagaube** [comment]
This issue is related to the Locations that Contributors add, i.e., dynamic content. We will have to manually audit the Locations and adjust/fix them if you don't want variety in the options shown in this drop down menu.

**Comment by dshaykewich** [comment]
Won't fix.
