### ISSUE TITLE
Home Page: Adjust spacing for better aesthetics & readability

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#68]
### Description 

Add bigger space/visual separation between Noteworthy sections and "Find learning events near you" title, and less space between Find Learning Events and the tabbed block.

![image](https://user-images.githubusercontent.com/34721375/45654628-58f0cb00-ba91-11e8-844f-32c47d2384db.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
Should be resolved via https://github.com/BCcampus/tlpd/commit/6f5343d7cdc841fb8ce370237f1556bd1ccfc6fc validation will require refreshing browser cache
