### ISSUE TITLE
Category default 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#69]
### Description 

Change default category from 'Uncategorized' to 'New'

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Changed default post category to "Events" in Settings > Writing

**Comment by bdolor** [comment]
thanks Jen, since this is a setting that lives in the dashboard, if you haven't already, then prod needs this love too.

**Comment by jgrajkowski** [comment]
Prod love complete.  Added categories 'Events' (default),'New + Noteworthy', 'Homepage'.  Also added 'Opportunities' and 'Resources' though these are not event types we're equipped for at the moment.
