### ISSUE TITLE
Replace references of EYPD in codebase with pro-d name or generic name 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#7]

**Comment by alexpflores** [comment]
For the initial commit the naming changed as follows:
EYPD = prod for function prefixs, and pro-d for file names or package name
Early Years Professional Development = Professional Development

The images will need to be renamed as well, assuming we're replacing those, the image paths in stlyesheets and code have changed to prod-image-name.png for example

**Comment by alexpflores** [comment]
@bdolor if your are okay with using pro-d this is done, or I can change depending on the naming decision tomorrow.

**Comment by bdolor** [comment]
Better to wait

**Comment by alexpflores** [comment]
ok, waiting on #1, will make the necessary changes if needed.

**Comment by alexpflores** [comment]
Completed via https://github.com/BCcampus/tlpd/commit/58f1a8692138b5bd7d3a8000076c50f06112028c

Replaced as follows: 
EYPD = TLPD
eypd = eypd
Early Years = Teaching and Learning Professional Development
Early Years Professional Development = Teaching and Learning Professional Development
