### ISSUE TITLE
New + noteworthy posts: Fix column display 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#70]
### Description 

New + noteworthy posts on the home page should be a three-column display

![image](https://user-images.githubusercontent.com/34721375/45654492-afa9d500-ba90-11e8-8dde-e9bbe6d4aed1.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
Should be resolved via https://github.com/BCcampus/tlpd/commit/dc0bf380badc50a82cce5b03b75a790449c36d76 validation will require refreshing browser cache. Note, the default image used will need to be increased in size in order to accommodate the adjustment in width.

**Comment by BCcLeva** [comment]
@jgrajkowski will need your help. I tried testing by creating a 3rd post and tagging but wasn't successful and the graphic needs to be adjusted per brad note above.

**Comment by jgrajkowski** [comment]
Updated graphic, moving back to Backlog for column + post fixes.

**Comment by alex-418** [comment]
@jgrajkowski can you please confirm i'm using this image and not the one in #65 ?

**Comment by jgrajkowski** [comment]
yeah, this is the one. updated #65 with 600px-width one to avoid confusion.

**Comment by alex-418** [comment]
3 columns added via https://github.com/BCcampus/tlpd/pull/103
