### ISSUE TITLE
Individual events page: Change heading 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#71]
### Description 

Change heading on left frame for individual event page and rename "Events" to "Upcoming events".

![image](https://user-images.githubusercontent.com/34721375/45654404-56da3c80-ba90-11e8-9460-6653f67c5e06.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by dshaykewich** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/43043264/45574742-d7493500-b825-11e8-8820-2b95c0c707b7.png">

**Comment by bdolor** [comment]
This is controlled by a widget in the dashboard, so will label non-dev. Looks like it's already been done on cert.
![image](https://user-images.githubusercontent.com/2048170/45982162-8814b880-c00c-11e8-9a17-41d48d86dff3.png)
