### ISSUE TITLE
New + Noteworthy posts: character limit

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#72]
### Description 

Add a character limit for New+Noteworthy posts e.g., "sketching in practice" blurb takes up a lot of space)

![image](https://user-images.githubusercontent.com/34721375/45654231-b1bf6400-ba8f-11e8-97db-3d897cd66ff1.png)

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
New char limit (25) added via https://github.com/BCcampus/tlpd/pull/103
