### ISSUE TITLE
Test iCal/Add to Calendar

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#73]
### Description 
Test iCal functionality to verify that it works properly.

**Expected behaviour** 

User will click on the iCal icon. Event will be populated in their calendar.

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
for my configuration at home and work (windows 10, google calendar or zimbra and in edge, FF or chrome), clicking the iCal link just brings up a download for the .ics file.  

tagging @BCcLeva and @paulagaube  as you likely have other Calendar setups (particularly Leva, on Mac).

**Comment by jgrajkowski** [comment]
Had @BCcLeva check this on iPhone and Macbook.
In both cases, clicking on iCal link adds the entry into her Calendar.

However, map display on iPhone is skewed. Leva says she'll create a new issue.
