### ISSUE TITLE
Individual event page: Change the order of how the fields/information is displayed

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#75]
Change the order of the items displayed in the record: Date/Time, Location, Presenters, Reg Fee, Reg Link, Share This, Description, Target Audience, Pre-requisites, Online, Event Open to External, Event Hosts (not Sponsors), iCal
Can REMOVE "Required Materials" "Registration Email" as we are a Referatory so this info should be on the web page we linkto and "Categories" as it appears at the top.

**Comment by alex-418** [comment]
Bring as close as possible (data is coming from multiple plugins)

**Comment by bdolor** [comment]
@BCcLeva - the two 'chunks' that we were talking about having some control over: 

**top 'chunk' - these come from default event fields controlled by events manager (presented below in the existing order)**
- location map
- date/time
- location link
- ical (calendar link)
- description
- categories
- bookings

**bottom 'chunk' - these are the extra 'attributes' that we have tacked on (presented below in the existing order)** 
```'#_ATT{Target Audience}
#_ATT{Event is open to external}{|Yes|No}
#_ATT{Online}{|Yes|No}
#_ATT{Registration Fee}
#_ATT{Registration Space}{|Filling Up!|FULL}
#_ATT{Registration Contact Phone Number}
#_ATT{Registration Link}
#_ATT{Prerequisite(s)}
#_ATT{Presenter(s)}
#_ATT{Presenter Information}
#_ATT{Event Hosts}';```

we can rearrange the order of items in 'chunk 1' and rearrange the order in 'chunk2' but we are unable to mix elements from chunk1 with chunk2. 

Please confirm that the order presented here meets your needs, or rearrange them within the relevant constraints - thanks

**Comment by bdolor** [comment]
Complete via https://github.com/BCcampus/tlpd/pull/94

**Comment by BCcLeva** [comment]
•	location map
•	date/time
•	location link
•	ical (calendar link)
•	description
•	categories
 


#_ATT{Presenter(s)}
#_ATT{Presenter Information}
#_ATT{Event Hosts}';
#_ATT{Target Audience}';
#_ATT{Event is open to external participants.}{|Yes|No}
#_ATT{Prerequisite(s)}
#_ATT{Registration Fee} 
#_ATT{Online}{|Yes|No}
#_ATT{Availability}{|Filling Up!|FULL}
#_ATT{Registration Link}
#_ATT{Registration Contact Phone Number}


I have removed "bookings" (chuck 1) and added "Target Audience"(chuck 2)
