### ISSUE TITLE
copy material for content owners 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#8]
we need new copy for the areas that aren't under user control 

*homepage*
- footer content is under user control, and can be modified

*about us*
- content for this page 

*terms and conditions* 
- content for this page

*privacy policy*
- content for this page

*contact us*
- content for this page

*help*
- content for this page

![image](https://user-images.githubusercontent.com/2048170/36687253-e72b4dcc-1add-11e8-855e-6648b8be15ad.png)

**Comment by BCcLeva** [comment]
Here is footer content for "About Us"
[TLPDAboutUs.docx](https://github.com/BCcampus/tlpd/files/1993372/TLPDAboutUs.docx)

**Comment by BCcLeva** [comment]
Here is footer content for "Privacy"
[TLPDFooterPrivacy.docx](https://github.com/BCcampus/tlpd/files/1993377/TLPDFooterPrivacy.docx)

**Comment by BCcLeva** [comment]
Here is footer content for "Terms and Conditions"

**Comment by BCcLeva** [comment]
Here is footer content for "Help"

Help
Find answers to Frequently Asked Questions or submit a question using our online form.

**Comment by BCcLeva** [comment]
"Contact Us" requires creation of an online form

**Comment by BCcLeva** [comment]
Footer content includes link to Creative Commons License
Attribution 4.0 International (CC:By 4.0)
https://creativecommons.org/licenses/by/4.0/

**Comment by BCcLeva** [comment]
Paula and Jen - can one of you help create the Online form ?

**Comment by bdolor** [comment]
@BCcLeva - This issue is only related to content, so what would be required prior to making a contact form is what that form would look like and what kind of messaging would be around that. I would recommend looking at the contact form plugin on the site (contact form 7) and making those decisions. A separate issue could be opened up to address the work of creating the form where anyone can self-assign.

**Comment by BCcLeva** [comment]
ok let's open up a separate issue for creating an Online form.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/cc20859f88f4fe59551f6fdb9a44dffa7327cded

**Comment by BCcLeva** [comment]
Please update the blurb as missing the acronym. Then it can be moved to Done.

The Teaching Learning Professional Development (TLPD) web portal is an initiative developed by BCcampus with the B.C. post-secondary educator community. The web portal aims to support post-secondary educators in promoting and finding teaching and learning professional development opportunities and support the building of community connections.
