### ISSUE TITLE
Resize logo to be smaller

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#80]
### Description 

Main logo is too big.  Please decrease by 20%.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/43043264/45575807-ba166580-b829-11e8-9b76-fd059afb10d5.png">

**Comment by bdolor** [comment]
@jgrajkowski - please remind me, if it was determined that this logo sizing issue was going to be resolved via providing an .svg?

**Comment by bdolor** [comment]
I think related to https://github.com/BCcampus/tlpd/issues/88. will mark both issues as blocked for now.

**Comment by jgrajkowski** [comment]
Looky, an SVG! (um, in the .ZIP because Github..)
[TLPD Logo.zip](https://github.com/BCcampus/tlpd/files/2403222/TLPD.Logo.zip)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/96 - mostly likely will require clearing browser cache to validate
