### ISSUE TITLE
Deployment to Prod site 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#81]
### Description 
What is the process for the development of the Prod site. Is this part of the same sprint or a new sprint?
What about data that is entered in the Dev site...Can that be ported into the Prod site?

[Description of the bug or feature]

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
Assuming all of the sprint backlog items are completed, push to production.

**Comment by alex-418** [comment]
Non-Dev Tasks that can be split off: 
- Plugin-configuration
- Content Creation
- Menu creation

**Comment by BCcLeva** [comment]
ok I'll work with @jgrajkowski @paulagaube on the Non-dev tasks
