### ISSUE TITLE
Posting an Event: Selecting Target Audience 

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#82]
### Description 
When a contributor creates and event they are able to easily select one or more target audience groups. 

**Expected behaviour** 
A list of target audience groups appears allowing for one or more selections. e.g. checkboxes

**Actual behaviour** 
The user is only able to make one selection from a pick list. 

### Steps to reproduce the problem
Login as a Contributor. Go to "Add an Event'. Go to "Target Audience". Click on the "+"
![screen shot 2018-12-09 at 5 35 44 pm](https://user-images.githubusercontent.com/34721375/49706680-34ae1180-fbdc-11e8-8ccf-70828ea38b48.png)

*Please change "Consultants" to "Facilitators" in this list.

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
Add a text input field for "other target audience", and a "target audience" select list @BCcLeva will provide. (These are attribute when creating an event)

**Comment by jgrajkowski** [comment]
@BCcLeva provide list

**Comment by BCcLeva** [comment]
Here's the list @alex-418 

Administrators
Consultants
Ed Developers
Ed Technologists/Media Developers
Faculty/Instructors
Instructional Designers
Information Technology staff
Librarians
Students
Teaching & Learning Staff 
Other

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/tlpd/commit/704bd3b66eb8bcd29e1937625ce48b298db3a4b6

**Comment by BCcLeva** [comment]
Is it possible for us to allow more than one choice from the pick list like the way Categories work?

**Comment by alex-418** [comment]
As per our discussion, will look into the events plugin provides a way to achieve that. Otherwise add a second text input box.

**Comment by alex-418** [comment]
New field: Target Audience - Other was added via https://github.com/BCcampus/tlpd/commit/8f24f6a58c0648b49ca8c393c2d96b2657256878

**Comment by paulagaube** [comment]
@bdolor I think this is a DEV task, not non-dev. If this is something I can change, can you tell me where please? 
The "Target Audience" drop down list does not quite reflect the list in Leva's comment on Sept 27 and Alex's follow up comment on Sept 28 (Added "Target Audience - Other"). 

Here is a screenshot, showing that the target audience "Students" is on this list twice, and these two audiences are missing from the list:
1. Teaching & Learning Staff
2. Target Audience - Other
<img width="576" alt="target-audience-dropdown" src="https://user-images.githubusercontent.com/26391359/50122658-6d6c6d00-0212-11e9-811a-8033f993e84f.png">

**Comment by paulagaube** [comment]
@bdolor Also, is it possible to add the sweet multiple choice fix to this field, as you did with Category?

**Comment by bdolor** [comment]
@paulagaube these are complete via https://github.com/BCcampus/tlpd/commit/b28733df7c01281757706dc33cf62194ce0888a5 and https://github.com/BCcampus/tlpd/commit/0aa9288bc61653b5874a9d097cbbc6e72337ef32 

Regarding adding the sweetness, unlike the categories which is set up to handle multiple select values the options available to us with these extra attributes are limited: https://wp-events-plugin.com/documentation/event-attributes/

**Comment by kkilbey** [comment]
Good stuff. Moving to Done.
