### ISSUE TITLE
Event Info - Fee/No Fee help text

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#83]
### Description 
Shall we make it a drop done that says "Fee" or "No Fee" ? 

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
If it's binary like this, a checkbox or radio button + place to add the cost should work, as opposed to a drop-down.  Or something similar.

**Comment by alex-418** [comment]
Plugin has limitations, might not be straight forward.

**Comment by alex-418** [comment]
@BCcLeva to create "help text" we could add to the field to solve this one.

**Comment by jgrajkowski** [comment]
@BCcLeva I did look at the options on this and didn't find an easy way to change to numerical-only values, so the 'help text' will probably be the most straightforward 'fix' here.

**Comment by BCcLeva** [comment]
The help text can be:
"Enter the registration fee ($CAD). Add notes as required; e.g., 'Free', 'No fee for internal staff'"

**Comment by jgrajkowski** [comment]
May be blind but am unsure if non-devs can add the 'help text'.  Removing non-dev.

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/tlpd/commit/aac8b9f5aacaf2d47bb881140ee77be1f0f9a9d5

**Comment by jgrajkowski** [comment]
Looks like anything with (s) is forces the S to be capitalized on titles at https://tlpddev.bccampus.ca/post-event/.  I have removed this plural via the settings.
