### ISSUE TITLE
Edit text at top of Post an Event page

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#86]
### Description 

Text at the top of this page is long and mentions contacting "earlyyears at bccampus.ca" https://tlpddev.bccampus.ca/post-event/

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Note: This is only the case when logged in.  Displays different message (about Learners, a user type we don't need) when not logged in, so both blurbs will need to be changed.

Non-logged in at /post-event should give direction on signing up/logging in.
Logged-in at /post-event requires changing the email address at minimum, probably shorten the blurb.

**Comment by paulagaube** [comment]
https://tlpddev.bccampus.ca/post-event/
While logged in the text at the top of this page says:

**Post an Event**

This form is to be completed in order to post events on this web portal. To add your event, fill in the fields below. Fields marked with an * are mandatory. If you have multiple events to post please contact earlyyears[at]bccampus.ca for assistance.

**Comment by jgrajkowski** [comment]
Not logged in:

**Looking to Learn?**
You are using this site in the role as a Learner. Learners may search for, share, and print events. Learners are not authorized to post events.
