### ISSUE TITLE
On Post an Event page, remove checkbox and text related to consent of submitted data

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#87]
### Description 

At the bottom of the Post an Event page, there is a checkbox that says "I consent to my submitted data being collected and stored as outlined by the site ." 
https://tlpddev.bccampus.ca/post-event/

**Expected behaviour** 

The information added on this page is for a public event and is not personal. Is this an appropriate checkbox for this page?

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
GDPR compliance suggest Positive opt-in: Get Positive opt-in (no pre-checked box) from users if they wish to use their data for export.

**Comment by jgrajkowski** [comment]
In Events > Settings > General tab > Privacy > Consent > flipped Booking Form, Event Submission Form, Location Submission Forms to "Do not include".
