### ISSUE TITLE
Need to display TLPD logo on Mobile device

### ISSUE THREAD

**Issue by BCcLeva** [BCcampus/tlpd#88]
### Description 

TLPD logo does not appear on cell phone.

**Comment by alex-418** [comment]
@jGrajkowski to provide svg logo

**Comment by bdolor** [comment]
resolved via #96 - mostly likely will require clearing browser cache to validate

**Comment by BCcLeva** [comment]
Logo looks fine on iphone vertical but not when viewing horizontal orientation - Graphics overlap.
Logo and top menu overlap as well on ipad.
