### ISSUE TITLE
Excel Export fixes

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#89]
### Description 

Tackle this fix: https://github.com/BCcampus/excel-export/issues/20

**Comment by alex-418** [comment]
Also completed in this was https://github.com/BCcampus/excel-export/issues/18

To validate, please visit your dashboard. Under the "Tools" menu you'll find "Excel Export". This allows you to export all of your user data, and post data (including custom post types, such as events) to Excel.

**Comment by paulagaube** [comment]
My first tests show this Export function works well and is slick.

We may want to look a bit closer at the fields that are exported and see if any refinements are needed later. Also want to review with @BCcLeva
