### ISSUE TITLE
copy for developers

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#9]
- remove myEYPD in header
- change 'search for training events' to 'learning' events
- remove showcase area from homepage

![image](https://user-images.githubusercontent.com/2048170/36687551-d70d476e-1ade-11e8-913c-586819273ec5.png)

![image](https://user-images.githubusercontent.com/2048170/36687568-deb98fd6-1ade-11e8-9e41-11a9a3c9f9b5.png)

![image](https://user-images.githubusercontent.com/2048170/36687579-e675bf56-1ade-11e8-9d4b-8cc18ac6b7c2.png)

![image](https://user-images.githubusercontent.com/2048170/36687593-f28aafe0-1ade-11e8-83df-88a70a02f609.png)

**Comment by BCcLeva** [comment]
Hi Brad, can you hide/remove the "My Tlpd" link in upper right corner?

**Comment by bdolor** [comment]
complete, via https://github.com/BCcampus/tlpd/commit/3fa545217b9f4e3163c5492543170100161b2484
