### ISSUE TITLE
Fix popovers

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#93]
### Description 

initialization of popovers is no longer working in BS4. The error is: `Uncaught TypeError: $(...).popover is not a function`

**Comment by jgrajkowski** [comment]
where do these popovers occur? i'm not familiar with these to validate.

**Comment by bdolor** [comment]
you have to be logged out, then click one of 'Add Event' 'Edit Event', or 'My Events'

**Comment by jgrajkowski** [comment]
ah, appears to be working correctly in Windows FF, Edge, and Chrome.

though should the login page have the BCcampus logo or TLPD logo? @BCcLeva let us know and create issue if change required.

also i assume dev's working on the Create page layout and that's why it looks odd right now. :)

**Comment by jgrajkowski** [comment]
Shows up small but fine on Android.

Can @BCcLeva or someone with a Mac or something confirm these come up OK?

**Comment by BCcLeva** [comment]
Checked popovers on my iphone 6 and they do not show at all (when tapping on "Add New" or "Edit Event".

Checked on my computer using FF and Chrome and popups work but the some of the text is hard to read on the black background. 

![screen shot 2018-09-27 at 2 59 01 pm](https://user-images.githubusercontent.com/34721375/46177265-1e441b00-c267-11e8-8578-ff43ca912a36.png)

**Comment by bdolor** [comment]
Looking at the title to get a sense of scope for this issue, a definition of 'done' seems to be that it's working. If it appears to be working in all but safari, my request is to capture that in a new issue (not working in safari mobile browser). If there is an issue with the readability, that work would also be best captured in a new issue. When creating new issues, please use the issue templates if you can - thanks! Moving this to done.

**Comment by BCcLeva** [comment]
ok. will create as new issue.
