### ISSUE TITLE
Configure the Validate by Domain plugin on Prod

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#95]
### Description 

Configure the Validate by Domain plugin on TLPD Prod when Prod is live.

Adding this task checklist:

1. Confirm that the Validate by Domain plugin is installed. Dashboard > Settings > Validate by Domain
2. Confirm with @BCcLeva if we are ready to Enable the plugin. If so, click Enable checkbox, otherwise, do not click checkbox.
3. Ask Brad or Alex for the Field Number if it is not already populated
4. Set the role to Contributor
5. Copy the Whitelist from tlpddev.bccampus.ca to tlpd.bccampus.ca
6. Settings > Validate by Domain > Whitelist
7. Save Changes

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment]
I activated the "BC Instititutions Domain Validator" on Prod and copied over the whitelist of BC institutions.
Need to know what number to put in the "Field number" before enabling the plugin. @bdolor or @alex-418 can you help? Is this a number I can find (I'm not sure where?) or do you need to get it out of a database?

**Comment by bdolor** [comment]
@paulagaube - First step is to create the fields for the sign up page in the dashboard under Users->Profile Fields. 

![image](https://user-images.githubusercontent.com/2048170/45965015-2b99a500-bfdc-11e8-9928-366b798bca42.png)

Cert/Prod both need these sign up fields created

**Comment by jgrajkowski** [comment]
I've tentatively configured the profile fields in Prod to match dev, @paulagaube though I believe Leva wants to chat about this later, so am just tagging you to do the rest as it sounds like you're familiar with the process.

**Comment by jgrajkowski** [comment]
@bdolor Can you confirm the field number for Validate By Domain? We're not sure how to determine or confirm said #.

**Comment by bdolor** [comment]
what do value do you currently have?

**Comment by paulagaube** [comment]
Step one complete: We updated the Users > Profile Fields on Prod
I made the field value "5", but this is fairly random.

**Comment by jgrajkowski** [comment]
i've flipped it to 2 on PROD to match DEV though my gmail accounts registered OK at that setting.

Paula had tried 5 but that didn't seem to work either I'm unsure what the logic is for the field #s or what else is missing.

**Comment by bdolor** [comment]
The field value is 2 for both prod/cert, however, the word/label 'Organizer' needs to accompany the correct field value. 

If you recall, the original intent behind validate by domain was to apply two sets of rules to two distinct groups, using the same sign-up form. It applies restriction by email domain to one group of people (Organizers) who were then assigned to a specific, elevated WP role and it does _not_ apply any email domain restrictions to another group of people (Learners) who were assigned to a less privileged WP role. If that use case doesn't really apply to the TLPD site, then it may not be the right solution. For now, the only way for validate by domain to work at restricting registration, is to have the label 'Organizer' and the field value '2'. 

If the goal is to hide if from users during the sign up stage, as a work around we could look at using CSS

**Comment by jgrajkowski** [comment]
My understanding is that Contributors/Organizers are the only user type here.  @BCcLeva  and @paulagaube and I had a bit of a conversation about this yesterday; I will defer to them for final decision.

**Comment by paulagaube** [comment]
Thanks Brad, I found the "Field_2" on the Input Radio button for Organizers in the Profile Fields so I understand now where that come from. And I see if we are going to keep the Validate by Domain plugin (which I assume we are), then we need to keep the Organizer radio button functionality.  

@BCcLeva do you want to hide the Organizer radio button on the Sign up page? If so, then we would need to create another ticket to ask for what Brad suggests: hiding that section with the CSS stylesheet. 

But for this ticket...I'm confirming this plugin is configured on Prod and ready to go live.
