### ISSUE TITLE
Change header and highlight colour on date picker

### ISSUE THREAD

**Issue by jgrajkowski** [BCcampus/tlpd#99]
Is presently an orange colour that looks odd against our palette.  

Current attributes:
background: #f6a828
border: 1px solid #e78f08

Suggested attributes:
background: #8e53a1 (deep purple), remove border?

<div class="ui-datepicker-header **ui-widget-header** ui-helper-clearfix ui-corner-all">

**Comment by bdolor** [comment]
resolved via #115

**Comment by BCcLeva** [comment]
can we change the highlight colour when you rollover calender dates to something that is within our colour palette?  green, light purple or blue?

**Comment by bdolor** [comment]
sure - when you decide which one, let us know.

**Comment by BCcLeva** [comment]
ok will need @jgrajkowski to help provide

**Comment by alex-418** [comment]
Changed to grey: #c4cbe0 via https://github.com/BCcampus/tlpd/commit/36829d340d473cc6d45bc33910ce5be4534de5c9

**Comment by bdolor** [comment]
so, my understanding of this ticket...there are two asks here.

1. change the header colour to purple (taken care of in #115 and undone in https://github.com/BCcampus/tlpd/commit/36829d340d473cc6d45bc33910ce5be4534de5c9)
2. change the roll over colour to a lighter shade of purple-gray (still not done)
